// Code generated by ent, DO NOT EDIT.

package productattr

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldName, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldMerchantID, v))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldStoreID, v))
}

// ProductCount applies equality check predicate on the "product_count" field. It's identical to ProductCountEQ.
func ProductCount(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldProductCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldContainsFold(FieldName, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldMerchantID, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v uuid.UUID) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldStoreID, v))
}

// ProductCountEQ applies the EQ predicate on the "product_count" field.
func ProductCountEQ(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldEQ(FieldProductCount, v))
}

// ProductCountNEQ applies the NEQ predicate on the "product_count" field.
func ProductCountNEQ(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNEQ(FieldProductCount, v))
}

// ProductCountIn applies the In predicate on the "product_count" field.
func ProductCountIn(vs ...int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldIn(FieldProductCount, vs...))
}

// ProductCountNotIn applies the NotIn predicate on the "product_count" field.
func ProductCountNotIn(vs ...int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldNotIn(FieldProductCount, vs...))
}

// ProductCountGT applies the GT predicate on the "product_count" field.
func ProductCountGT(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGT(FieldProductCount, v))
}

// ProductCountGTE applies the GTE predicate on the "product_count" field.
func ProductCountGTE(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldGTE(FieldProductCount, v))
}

// ProductCountLT applies the LT predicate on the "product_count" field.
func ProductCountLT(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLT(FieldProductCount, v))
}

// ProductCountLTE applies the LTE predicate on the "product_count" field.
func ProductCountLTE(v int) predicate.ProductAttr {
	return predicate.ProductAttr(sql.FieldLTE(FieldProductCount, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.ProductAttr {
	return predicate.ProductAttr(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.ProductAttrItem) predicate.ProductAttr {
	return predicate.ProductAttr(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductAttrs applies the HasEdge predicate on the "product_attrs" edge.
func HasProductAttrs() predicate.ProductAttr {
	return predicate.ProductAttr(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProductAttrsTable, ProductAttrsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductAttrsWith applies the HasEdge predicate on the "product_attrs" edge with a given conditions (other predicates).
func HasProductAttrsWith(preds ...predicate.ProductAttrRelation) predicate.ProductAttr {
	return predicate.ProductAttr(func(s *sql.Selector) {
		step := newProductAttrsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductAttr) predicate.ProductAttr {
	return predicate.ProductAttr(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductAttr) predicate.ProductAttr {
	return predicate.ProductAttr(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductAttr) predicate.ProductAttr {
	return predicate.ProductAttr(sql.NotPredicates(p))
}
