// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: BusinessConfigInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
)

// MockBusinessConfigInteractor is a mock of BusinessConfigInteractor interface.
type MockBusinessConfigInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessConfigInteractorMockRecorder
}

// MockBusinessConfigInteractorMockRecorder is the mock recorder for MockBusinessConfigInteractor.
type MockBusinessConfigInteractorMockRecorder struct {
	mock *MockBusinessConfigInteractor
}

// NewMockBusinessConfigInteractor creates a new mock instance.
func NewMockBusinessConfigInteractor(ctrl *gomock.Controller) *MockBusinessConfigInteractor {
	mock := &MockBusinessConfigInteractor{ctrl: ctrl}
	mock.recorder = &MockBusinessConfigInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessConfigInteractor) EXPECT() *MockBusinessConfigInteractorMockRecorder {
	return m.recorder
}

// ListBySearch mocks base method.
func (m *MockBusinessConfigInteractor) ListBySearch(arg0 context.Context, arg1 domain.BusinessConfigSearchParams) (*domain.BusinessConfigSearchRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySearch", arg0, arg1)
	ret0, _ := ret[0].(*domain.BusinessConfigSearchRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySearch indicates an expected call of ListBySearch.
func (mr *MockBusinessConfigInteractorMockRecorder) ListBySearch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySearch", reflect.TypeOf((*MockBusinessConfigInteractor)(nil).ListBySearch), arg0, arg1)
}
