// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: DataCache)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
)

// MockDataCache is a mock of DataCache interface.
type MockDataCache struct {
	ctrl     *gomock.Controller
	recorder *MockDataCacheMockRecorder
}

// MockDataCacheMockRecorder is the mock recorder for MockDataCache.
type MockDataCacheMockRecorder struct {
	mock *MockDataCache
}

// NewMockDataCache creates a new mock instance.
func NewMockDataCache(ctrl *gomock.Controller) *MockDataCache {
	mock := &MockDataCache{ctrl: ctrl}
	mock.recorder = &MockDataCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataCache) EXPECT() *MockDataCacheMockRecorder {
	return m.recorder
}

// GetFrontendUser mocks base method.
func (m *MockDataCache) GetFrontendUser(arg0 context.Context, arg1 int) (*domain.FrontendUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrontendUser", arg0, arg1)
	ret0, _ := ret[0].(*domain.FrontendUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFrontendUser indicates an expected call of GetFrontendUser.
func (mr *MockDataCacheMockRecorder) GetFrontendUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrontendUser", reflect.TypeOf((*MockDataCache)(nil).GetFrontendUser), arg0, arg1)
}

// GetStore mocks base method.
func (m *MockDataCache) GetStore(arg0 context.Context, arg1 int) (*domain.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", arg0, arg1)
	ret0, _ := ret[0].(*domain.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockDataCacheMockRecorder) GetStore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockDataCache)(nil).GetStore), arg0, arg1)
}

// SetFrontendUser mocks base method.
func (m *MockDataCache) SetFrontendUser(arg0 context.Context, arg1 *domain.FrontendUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFrontendUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFrontendUser indicates an expected call of SetFrontendUser.
func (mr *MockDataCacheMockRecorder) SetFrontendUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFrontendUser", reflect.TypeOf((*MockDataCache)(nil).SetFrontendUser), arg0, arg1)
}

// SetStore mocks base method.
func (m *MockDataCache) SetStore(arg0 context.Context, arg1 *domain.Store) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStore indicates an expected call of SetStore.
func (mr *MockDataCacheMockRecorder) SetStore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStore", reflect.TypeOf((*MockDataCache)(nil).SetStore), arg0, arg1)
}
