// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: DataCache)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockDataCache is a mock of DataCache interface.
type MockDataCache struct {
	ctrl     *gomock.Controller
	recorder *MockDataCacheMockRecorder
}

// MockDataCacheMockRecorder is the mock recorder for MockDataCache.
type MockDataCacheMockRecorder struct {
	mock *MockDataCache
}

// NewMockDataCache creates a new mock instance.
func NewMockDataCache(ctrl *gomock.Controller) *MockDataCache {
	mock := &MockDataCache{ctrl: ctrl}
	mock.recorder = &MockDataCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataCache) EXPECT() *MockDataCacheMockRecorder {
	return m.recorder
}
