// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: FrontendUserInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
	upagination "gitlab.jiguang.dev/pos-dine/dine/pkg/upagination"
)

// MockFrontendUserInteractor is a mock of FrontendUserInteractor interface.
type MockFrontendUserInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockFrontendUserInteractorMockRecorder
}

// MockFrontendUserInteractorMockRecorder is the mock recorder for MockFrontendUserInteractor.
type MockFrontendUserInteractorMockRecorder struct {
	mock *MockFrontendUserInteractor
}

// NewMockFrontendUserInteractor creates a new mock instance.
func NewMockFrontendUserInteractor(ctrl *gomock.Controller) *MockFrontendUserInteractor {
	mock := &MockFrontendUserInteractor{ctrl: ctrl}
	mock.recorder = &MockFrontendUserInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrontendUserInteractor) EXPECT() *MockFrontendUserInteractorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockFrontendUserInteractor) Authenticate(arg0 context.Context, arg1 string) (*domain.FrontendUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", arg0, arg1)
	ret0, _ := ret[0].(*domain.FrontendUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockFrontendUserInteractorMockRecorder) Authenticate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Authenticate), arg0, arg1)
}

// Create mocks base method.
func (m *MockFrontendUserInteractor) Create(arg0 context.Context, arg1 *domain.FrontendUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFrontendUserInteractorMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockFrontendUserInteractor) Find(arg0 context.Context, arg1 int) (*domain.FrontendUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*domain.FrontendUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockFrontendUserInteractorMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Find), arg0, arg1)
}

// List mocks base method.
func (m *MockFrontendUserInteractor) List(arg0 context.Context, arg1 *upagination.Pagination, arg2 *domain.FrontendUserListFilter) ([]*domain.FrontendUser, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.FrontendUser)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockFrontendUserInteractorMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFrontendUserInteractor)(nil).List), arg0, arg1, arg2)
}

// Login mocks base method.
func (m *MockFrontendUserInteractor) Login(arg0 context.Context, arg1, arg2 string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockFrontendUserInteractorMockRecorder) Login(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Login), arg0, arg1, arg2)
}

// Logout mocks base method.
func (m *MockFrontendUserInteractor) Logout(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockFrontendUserInteractorMockRecorder) Logout(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Logout), arg0)
}

// Update mocks base method.
func (m *MockFrontendUserInteractor) Update(arg0 context.Context, arg1 *domain.FrontendUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFrontendUserInteractorMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFrontendUserInteractor)(nil).Update), arg0, arg1)
}
