// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: OrderCartInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
)

// MockOrderCartInteractor is a mock of OrderCartInteractor interface.
type MockOrderCartInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderCartInteractorMockRecorder
}

// MockOrderCartInteractorMockRecorder is the mock recorder for MockOrderCartInteractor.
type MockOrderCartInteractorMockRecorder struct {
	mock *MockOrderCartInteractor
}

// NewMockOrderCartInteractor creates a new mock instance.
func NewMockOrderCartInteractor(ctrl *gomock.Controller) *MockOrderCartInteractor {
	mock := &MockOrderCartInteractor{ctrl: ctrl}
	mock.recorder = &MockOrderCartInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderCartInteractor) EXPECT() *MockOrderCartInteractorMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockOrderCartInteractor) AddItem(arg0 context.Context, arg1 domain.OrderCartAddParams) (domain.OrderCarts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", arg0, arg1)
	ret0, _ := ret[0].(domain.OrderCarts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockOrderCartInteractorMockRecorder) AddItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockOrderCartInteractor)(nil).AddItem), arg0, arg1)
}

// ListByTable mocks base method.
func (m *MockOrderCartInteractor) ListByTable(arg0 context.Context, arg1 int) (domain.OrderCarts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTable", arg0, arg1)
	ret0, _ := ret[0].(domain.OrderCarts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTable indicates an expected call of ListByTable.
func (mr *MockOrderCartInteractorMockRecorder) ListByTable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTable", reflect.TypeOf((*MockOrderCartInteractor)(nil).ListByTable), arg0, arg1)
}

// RemoveItem mocks base method.
func (m *MockOrderCartInteractor) RemoveItem(arg0 context.Context, arg1, arg2 int) (domain.OrderCarts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.OrderCarts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockOrderCartInteractorMockRecorder) RemoveItem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockOrderCartInteractor)(nil).RemoveItem), arg0, arg1, arg2)
}
