// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: ProductInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
)

// MockProductInteractor is a mock of ProductInteractor interface.
type MockProductInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockProductInteractorMockRecorder
}

// MockProductInteractorMockRecorder is the mock recorder for MockProductInteractor.
type MockProductInteractorMockRecorder struct {
	mock *MockProductInteractor
}

// NewMockProductInteractor creates a new mock instance.
func NewMockProductInteractor(ctrl *gomock.Controller) *MockProductInteractor {
	mock := &MockProductInteractor{ctrl: ctrl}
	mock.recorder = &MockProductInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductInteractor) EXPECT() *MockProductInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductInteractor) Create(arg0 context.Context, arg1 *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductInteractorMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductInteractor)(nil).Create), arg0, arg1)
}
