// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: StallInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
	upagination "gitlab.jiguang.dev/pos-dine/dine/pkg/upagination"
)

// MockStallInteractor is a mock of StallInteractor interface.
type MockStallInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockStallInteractorMockRecorder
}

// MockStallInteractorMockRecorder is the mock recorder for MockStallInteractor.
type MockStallInteractorMockRecorder struct {
	mock *MockStallInteractor
}

// NewMockStallInteractor creates a new mock instance.
func NewMockStallInteractor(ctrl *gomock.Controller) *MockStallInteractor {
	mock := &MockStallInteractor{ctrl: ctrl}
	mock.recorder = &MockStallInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStallInteractor) EXPECT() *MockStallInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStallInteractor) Create(arg0 context.Context, arg1 *domain.Stall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStallInteractorMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStallInteractor)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockStallInteractor) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStallInteractorMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStallInteractor)(nil).Delete), arg0, arg1)
}

// GetStall mocks base method.
func (m *MockStallInteractor) GetStall(arg0 context.Context, arg1 uuid.UUID) (*domain.Stall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStall", arg0, arg1)
	ret0, _ := ret[0].(*domain.Stall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStall indicates an expected call of GetStall.
func (mr *MockStallInteractorMockRecorder) GetStall(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStall", reflect.TypeOf((*MockStallInteractor)(nil).GetStall), arg0, arg1)
}

// GetStalls mocks base method.
func (m *MockStallInteractor) GetStalls(arg0 context.Context, arg1 *upagination.Pagination, arg2 *domain.StallListFilter, arg3 ...domain.StallOrderBy) ([]*domain.Stall, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStalls", varargs...)
	ret0, _ := ret[0].([]*domain.Stall)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStalls indicates an expected call of GetStalls.
func (mr *MockStallInteractorMockRecorder) GetStalls(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStalls", reflect.TypeOf((*MockStallInteractor)(nil).GetStalls), varargs...)
}

// StallSimpleUpdate mocks base method.
func (m *MockStallInteractor) StallSimpleUpdate(arg0 context.Context, arg1 domain.StallSimpleUpdateField, arg2 *domain.Stall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StallSimpleUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StallSimpleUpdate indicates an expected call of StallSimpleUpdate.
func (mr *MockStallInteractorMockRecorder) StallSimpleUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StallSimpleUpdate", reflect.TypeOf((*MockStallInteractor)(nil).StallSimpleUpdate), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockStallInteractor) Update(arg0 context.Context, arg1 *domain.Stall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStallInteractorMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStallInteractor)(nil).Update), arg0, arg1)
}
