// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: TaxFeeInteractor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
	upagination "gitlab.jiguang.dev/pos-dine/dine/pkg/upagination"
)

// MockTaxFeeInteractor is a mock of TaxFeeInteractor interface.
type MockTaxFeeInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockTaxFeeInteractorMockRecorder
}

// MockTaxFeeInteractorMockRecorder is the mock recorder for MockTaxFeeInteractor.
type MockTaxFeeInteractorMockRecorder struct {
	mock *MockTaxFeeInteractor
}

// NewMockTaxFeeInteractor creates a new mock instance.
func NewMockTaxFeeInteractor(ctrl *gomock.Controller) *MockTaxFeeInteractor {
	mock := &MockTaxFeeInteractor{ctrl: ctrl}
	mock.recorder = &MockTaxFeeInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxFeeInteractor) EXPECT() *MockTaxFeeInteractorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaxFeeInteractor) Create(arg0 context.Context, arg1 *domain.TaxFee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaxFeeInteractorMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaxFeeInteractor)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTaxFeeInteractor) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaxFeeInteractorMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaxFeeInteractor)(nil).Delete), arg0, arg1)
}

// GetTaxFee mocks base method.
func (m *MockTaxFeeInteractor) GetTaxFee(arg0 context.Context, arg1 uuid.UUID) (*domain.TaxFee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaxFee", arg0, arg1)
	ret0, _ := ret[0].(*domain.TaxFee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaxFee indicates an expected call of GetTaxFee.
func (mr *MockTaxFeeInteractorMockRecorder) GetTaxFee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxFee", reflect.TypeOf((*MockTaxFeeInteractor)(nil).GetTaxFee), arg0, arg1)
}

// GetTaxFees mocks base method.
func (m *MockTaxFeeInteractor) GetTaxFees(arg0 context.Context, arg1 *upagination.Pagination, arg2 *domain.TaxFeeListFilter, arg3 ...domain.TaxFeeOrderBy) ([]*domain.TaxFee, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTaxFees", varargs...)
	ret0, _ := ret[0].([]*domain.TaxFee)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTaxFees indicates an expected call of GetTaxFees.
func (mr *MockTaxFeeInteractorMockRecorder) GetTaxFees(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaxFees", reflect.TypeOf((*MockTaxFeeInteractor)(nil).GetTaxFees), varargs...)
}

// TaxFeeSimpleUpdate mocks base method.
func (m *MockTaxFeeInteractor) TaxFeeSimpleUpdate(arg0 context.Context, arg1 domain.TaxFeeSimpleUpdateType, arg2 *domain.TaxFee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaxFeeSimpleUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaxFeeSimpleUpdate indicates an expected call of TaxFeeSimpleUpdate.
func (mr *MockTaxFeeInteractorMockRecorder) TaxFeeSimpleUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaxFeeSimpleUpdate", reflect.TypeOf((*MockTaxFeeInteractor)(nil).TaxFeeSimpleUpdate), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockTaxFeeInteractor) Update(arg0 context.Context, arg1 *domain.TaxFee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaxFeeInteractorMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaxFeeInteractor)(nil).Update), arg0, arg1)
}
