// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.jiguang.dev/pos-dine/dine/domain (interfaces: UserRoleRepository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "gitlab.jiguang.dev/pos-dine/dine/domain"
	upagination "gitlab.jiguang.dev/pos-dine/dine/pkg/upagination"
)

// MockUserRoleRepository is a mock of UserRoleRepository interface.
type MockUserRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleRepositoryMockRecorder
}

// MockUserRoleRepositoryMockRecorder is the mock recorder for MockUserRoleRepository.
type MockUserRoleRepositoryMockRecorder struct {
	mock *MockUserRoleRepository
}

// NewMockUserRoleRepository creates a new mock instance.
func NewMockUserRoleRepository(ctrl *gomock.Controller) *MockUserRoleRepository {
	mock := &MockUserRoleRepository{ctrl: ctrl}
	mock.recorder = &MockUserRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleRepository) EXPECT() *MockUserRoleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRoleRepository) Create(arg0 context.Context, arg1 *domain.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRoleRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRoleRepository)(nil).Create), arg0, arg1)
}

// CreateBulk mocks base method.
func (m *MockUserRoleRepository) CreateBulk(arg0 context.Context, arg1 []*domain.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBulk indicates an expected call of CreateBulk.
func (mr *MockUserRoleRepositoryMockRecorder) CreateBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulk", reflect.TypeOf((*MockUserRoleRepository)(nil).CreateBulk), arg0, arg1)
}

// CreateBulkByRoleIDUsers mocks base method.
func (m *MockUserRoleRepository) CreateBulkByRoleIDUsers(arg0 context.Context, arg1 uuid.UUID, arg2 []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulkByRoleIDUsers", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBulkByRoleIDUsers indicates an expected call of CreateBulkByRoleIDUsers.
func (mr *MockUserRoleRepositoryMockRecorder) CreateBulkByRoleIDUsers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulkByRoleIDUsers", reflect.TypeOf((*MockUserRoleRepository)(nil).CreateBulkByRoleIDUsers), arg0, arg1, arg2)
}

// CreateBulkByUserIDRoles mocks base method.
func (m *MockUserRoleRepository) CreateBulkByUserIDRoles(arg0 context.Context, arg1 domain.User, arg2 []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulkByUserIDRoles", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBulkByUserIDRoles indicates an expected call of CreateBulkByUserIDRoles.
func (mr *MockUserRoleRepositoryMockRecorder) CreateBulkByUserIDRoles(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulkByUserIDRoles", reflect.TypeOf((*MockUserRoleRepository)(nil).CreateBulkByUserIDRoles), arg0, arg1, arg2)
}

// DeleteByRoles mocks base method.
func (m *MockUserRoleRepository) DeleteByRoles(arg0 context.Context, arg1 ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteByRoles", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRoles indicates an expected call of DeleteByRoles.
func (mr *MockUserRoleRepositoryMockRecorder) DeleteByRoles(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRoles", reflect.TypeOf((*MockUserRoleRepository)(nil).DeleteByRoles), varargs...)
}

// DeleteByUsers mocks base method.
func (m *MockUserRoleRepository) DeleteByUsers(arg0 context.Context, arg1 domain.UserType, arg2 ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteByUsers", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUsers indicates an expected call of DeleteByUsers.
func (mr *MockUserRoleRepositoryMockRecorder) DeleteByUsers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUsers", reflect.TypeOf((*MockUserRoleRepository)(nil).DeleteByUsers), varargs...)
}

// Deletes mocks base method.
func (m *MockUserRoleRepository) Deletes(arg0 context.Context, arg1 ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Deletes", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deletes indicates an expected call of Deletes.
func (mr *MockUserRoleRepositoryMockRecorder) Deletes(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deletes", reflect.TypeOf((*MockUserRoleRepository)(nil).Deletes), varargs...)
}

// FindByID mocks base method.
func (m *MockUserRoleRepository) FindByID(arg0 context.Context, arg1 uuid.UUID) (*domain.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRoleRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRoleRepository)(nil).FindByID), arg0, arg1)
}

// FindOneByUser mocks base method.
func (m *MockUserRoleRepository) FindOneByUser(arg0 context.Context, arg1 domain.User) (*domain.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUser", arg0, arg1)
	ret0, _ := ret[0].(*domain.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUser indicates an expected call of FindOneByUser.
func (mr *MockUserRoleRepositoryMockRecorder) FindOneByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUser", reflect.TypeOf((*MockUserRoleRepository)(nil).FindOneByUser), arg0, arg1)
}

// GetByRoleIDs mocks base method.
func (m *MockUserRoleRepository) GetByRoleIDs(arg0 context.Context, arg1 domain.UserType, arg2 ...uuid.UUID) ([]*domain.UserRole, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByRoleIDs", varargs...)
	ret0, _ := ret[0].([]*domain.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleIDs indicates an expected call of GetByRoleIDs.
func (mr *MockUserRoleRepositoryMockRecorder) GetByRoleIDs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleIDs", reflect.TypeOf((*MockUserRoleRepository)(nil).GetByRoleIDs), varargs...)
}

// GetByUserIDs mocks base method.
func (m *MockUserRoleRepository) GetByUserIDs(arg0 context.Context, arg1 domain.UserType, arg2 ...uuid.UUID) ([]*domain.UserRole, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByUserIDs", varargs...)
	ret0, _ := ret[0].([]*domain.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDs indicates an expected call of GetByUserIDs.
func (mr *MockUserRoleRepositoryMockRecorder) GetByUserIDs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDs", reflect.TypeOf((*MockUserRoleRepository)(nil).GetByUserIDs), varargs...)
}

// GetUserRoles mocks base method.
func (m *MockUserRoleRepository) GetUserRoles(arg0 context.Context, arg1 *upagination.Pagination, arg2 *domain.UserRoleListFilter, arg3 ...domain.UserRoleListOrderBy) ([]*domain.UserRole, int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserRoles", varargs...)
	ret0, _ := ret[0].([]*domain.UserRole)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockUserRoleRepositoryMockRecorder) GetUserRoles(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockUserRoleRepository)(nil).GetUserRoles), varargs...)
}

// Update mocks base method.
func (m *MockUserRoleRepository) Update(arg0 context.Context, arg1 *domain.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRoleRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRoleRepository)(nil).Update), arg0, arg1)
}
