// Code generated by ent, DO NOT EDIT.

package paymentaccount

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"gitlab.jiguang.dev/pos-dine/dine/domain"
)

const (
	// Label holds the string label denoting the paymentaccount type in the database.
	Label = "payment_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldMerchantID holds the string denoting the merchant_id field in the database.
	FieldMerchantID = "merchant_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldMerchantNumber holds the string denoting the merchant_number field in the database.
	FieldMerchantNumber = "merchant_number"
	// FieldMerchantName holds the string denoting the merchant_name field in the database.
	FieldMerchantName = "merchant_name"
	// Table holds the table name of the paymentaccount in the database.
	Table = "payment_accounts"
)

// Columns holds all SQL columns for paymentaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldMerchantID,
	FieldChannel,
	FieldMerchantNumber,
	FieldMerchantName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "gitlab.jiguang.dev/pos-dine/dine/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int64
	// MerchantNumberValidator is a validator for the "merchant_number" field. It is called by the builders before save.
	MerchantNumberValidator func(string) error
	// MerchantNameValidator is a validator for the "merchant_name" field. It is called by the builders before save.
	MerchantNameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c domain.PaymentChannel) error {
	switch c {
	case "rm":
		return nil
	default:
		return fmt.Errorf("paymentaccount: invalid enum value for channel field: %q", c)
	}
}

// OrderOption defines the ordering options for the PaymentAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByMerchantID orders the results by the merchant_id field.
func ByMerchantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByMerchantNumber orders the results by the merchant_number field.
func ByMerchantNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantNumber, opts...).ToFunc()
}

// ByMerchantName orders the results by the merchant_name field.
func ByMerchantName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantName, opts...).ToFunc()
}
