package usecasefx

import (
	"gitlab.jiguang.dev/pos-dine/dine/domain"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/additionalfee"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/category"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/department"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/device"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/menu"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/merchant"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/order"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/permission"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/product"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/productattr"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/productspec"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/producttag"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/productunit"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/region"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/remark"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/role"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/routermenu"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/stall"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/store"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/taxfee"
	"gitlab.jiguang.dev/pos-dine/dine/usecase/userauth"
	"go.uber.org/fx"
)

var Module = fx.Module(
	"usecase",
	fx.Provide(
		fx.Annotate(
			userauth.NewAdminUserInteractor,
			fx.As(new(domain.AdminUserInteractor)),
		),
		fx.Annotate(
			category.NewCategoryInteractor,
			fx.As(new(domain.CategoryInteractor)),
		),
		fx.Annotate(
			userauth.NewBackendUserInteractor,
			fx.As(new(domain.BackendUserInteractor)),
		),
		fx.Annotate(
			productunit.NewProductUnitInteractor,
			fx.As(new(domain.ProductUnitInteractor)),
		),
		fx.Annotate(
			productspec.NewProductSpecInteractor,
			fx.As(new(domain.ProductSpecInteractor)),
		),
		fx.Annotate(
			producttag.NewProductTagInteractor,
			fx.As(new(domain.ProductTagInteractor)),
		),
		fx.Annotate(
			productattr.NewProductAttrInteractor,
			fx.As(new(domain.ProductAttrInteractor)),
		),
		fx.Annotate(
			product.NewProductInteractor,
			fx.As(new(domain.ProductInteractor)),
		),
		fx.Annotate(
			merchant.NewMerchantInteractor,
			fx.As(new(domain.MerchantInteractor)),
		),
		fx.Annotate(
			store.NewStoreInteractor,
			fx.As(new(domain.StoreInteractor)),
		),
		fx.Annotate(
			order.NewOrderInteractor,
			fx.As(new(domain.OrderInteractor)),
		),
		fx.Annotate(
			remark.NewRemarkInteractor,
			fx.As(new(domain.RemarkInteractor)),
		),
		fx.Annotate(
			remark.NewRemarkCategoryInteractor,
			fx.As(new(domain.RemarkCategoryInteractor)),
		),
		fx.Annotate(
			stall.NewStallInteractor,
			fx.As(new(domain.StallInteractor)),
		),
		fx.Annotate(
			additionalfee.NewAdditionalFeeInteractor,
			fx.As(new(domain.AdditionalFeeInteractor)),
		),
		fx.Annotate(
			taxfee.NewTaxFeeInteractor,
			fx.As(new(domain.TaxFeeInteractor)),
		),
		fx.Annotate(
			device.NewDeviceInteractor,
			fx.As(new(domain.DeviceInteractor)),
		),
		fx.Annotate(
			region.NewCountryInteractor,
			fx.As(new(domain.CountryInteractor)),
		),
		fx.Annotate(
			region.NewProvinceInteractor,
			fx.As(new(domain.ProvinceInteractor)),
		),
		fx.Annotate(
			menu.NewMenuInteractor,
			fx.As(new(domain.MenuInteractor)),
		),
		fx.Annotate(
			userauth.NewStoreUserInteractor,
			fx.As(new(domain.StoreUserInteractor)),
		),
		fx.Annotate(
			merchant.NewMerchantBusinessTypeInteractor,
			fx.As(new(domain.MerchantBusinessTypeInteractor)),
		),
		fx.Annotate(
			department.NewDepartmentInteractor,
			fx.As(new(domain.DepartmentInteractor)),
		),
		fx.Annotate(
			permission.NewPermissionInteractor,
			fx.As(new(domain.PermissionInteractor)),
		),
		fx.Annotate(
			routermenu.NewRouterMenuInteractor,
			fx.As(new(domain.RouterMenuInteractor)),
		),
		fx.Annotate(
			role.NewRoleInteractor,
			fx.As(new(domain.RoleInteractor)),
		),
	),
)
