// Code generated by ent, DO NOT EDIT.

package store

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"gitlab.jiguang.dev/pos-dine/dine/domain"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDeletedAt, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldMerchantID, v))
}

// AdminPhoneNumber applies equality check predicate on the "admin_phone_number" field. It's identical to AdminPhoneNumberEQ.
func AdminPhoneNumber(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldAdminPhoneNumber, v))
}

// StoreName applies equality check predicate on the "store_name" field. It's identical to StoreNameEQ.
func StoreName(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreName, v))
}

// StoreShortName applies equality check predicate on the "store_short_name" field. It's identical to StoreShortNameEQ.
func StoreShortName(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreShortName, v))
}

// StoreCode applies equality check predicate on the "store_code" field. It's identical to StoreCodeEQ.
func StoreCode(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreCode, v))
}

// BusinessTypeID applies equality check predicate on the "business_type_id" field. It's identical to BusinessTypeIDEQ.
func BusinessTypeID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldBusinessTypeID, v))
}

// LocationNumber applies equality check predicate on the "location_number" field. It's identical to LocationNumberEQ.
func LocationNumber(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLocationNumber, v))
}

// ContactName applies equality check predicate on the "contact_name" field. It's identical to ContactNameEQ.
func ContactName(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldContactName, v))
}

// ContactPhone applies equality check predicate on the "contact_phone" field. It's identical to ContactPhoneEQ.
func ContactPhone(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldContactPhone, v))
}

// UnifiedSocialCreditCode applies equality check predicate on the "unified_social_credit_code" field. It's identical to UnifiedSocialCreditCodeEQ.
func UnifiedSocialCreditCode(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldUnifiedSocialCreditCode, v))
}

// StoreLogo applies equality check predicate on the "store_logo" field. It's identical to StoreLogoEQ.
func StoreLogo(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreLogo, v))
}

// BusinessLicenseURL applies equality check predicate on the "business_license_url" field. It's identical to BusinessLicenseURLEQ.
func BusinessLicenseURL(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldBusinessLicenseURL, v))
}

// StorefrontURL applies equality check predicate on the "storefront_url" field. It's identical to StorefrontURLEQ.
func StorefrontURL(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStorefrontURL, v))
}

// CashierDeskURL applies equality check predicate on the "cashier_desk_url" field. It's identical to CashierDeskURLEQ.
func CashierDeskURL(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCashierDeskURL, v))
}

// DiningEnvironmentURL applies equality check predicate on the "dining_environment_url" field. It's identical to DiningEnvironmentURLEQ.
func DiningEnvironmentURL(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDiningEnvironmentURL, v))
}

// FoodOperationLicenseURL applies equality check predicate on the "food_operation_license_url" field. It's identical to FoodOperationLicenseURLEQ.
func FoodOperationLicenseURL(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldFoodOperationLicenseURL, v))
}

// CountryID applies equality check predicate on the "country_id" field. It's identical to CountryIDEQ.
func CountryID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCountryID, v))
}

// ProvinceID applies equality check predicate on the "province_id" field. It's identical to ProvinceIDEQ.
func ProvinceID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldProvinceID, v))
}

// CityID applies equality check predicate on the "city_id" field. It's identical to CityIDEQ.
func CityID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCityID, v))
}

// DistrictID applies equality check predicate on the "district_id" field. It's identical to DistrictIDEQ.
func DistrictID(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDistrictID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldAddress, v))
}

// Lng applies equality check predicate on the "lng" field. It's identical to LngEQ.
func Lng(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLng, v))
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLat, v))
}

// SuperAccount applies equality check predicate on the "super_account" field. It's identical to SuperAccountEQ.
func SuperAccount(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldSuperAccount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldDeletedAt, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldMerchantID, vs...))
}

// AdminPhoneNumberEQ applies the EQ predicate on the "admin_phone_number" field.
func AdminPhoneNumberEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberNEQ applies the NEQ predicate on the "admin_phone_number" field.
func AdminPhoneNumberNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberIn applies the In predicate on the "admin_phone_number" field.
func AdminPhoneNumberIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldAdminPhoneNumber, vs...))
}

// AdminPhoneNumberNotIn applies the NotIn predicate on the "admin_phone_number" field.
func AdminPhoneNumberNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldAdminPhoneNumber, vs...))
}

// AdminPhoneNumberGT applies the GT predicate on the "admin_phone_number" field.
func AdminPhoneNumberGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberGTE applies the GTE predicate on the "admin_phone_number" field.
func AdminPhoneNumberGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberLT applies the LT predicate on the "admin_phone_number" field.
func AdminPhoneNumberLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberLTE applies the LTE predicate on the "admin_phone_number" field.
func AdminPhoneNumberLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberContains applies the Contains predicate on the "admin_phone_number" field.
func AdminPhoneNumberContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberHasPrefix applies the HasPrefix predicate on the "admin_phone_number" field.
func AdminPhoneNumberHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberHasSuffix applies the HasSuffix predicate on the "admin_phone_number" field.
func AdminPhoneNumberHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberEqualFold applies the EqualFold predicate on the "admin_phone_number" field.
func AdminPhoneNumberEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldAdminPhoneNumber, v))
}

// AdminPhoneNumberContainsFold applies the ContainsFold predicate on the "admin_phone_number" field.
func AdminPhoneNumberContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldAdminPhoneNumber, v))
}

// StoreNameEQ applies the EQ predicate on the "store_name" field.
func StoreNameEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreName, v))
}

// StoreNameNEQ applies the NEQ predicate on the "store_name" field.
func StoreNameNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldStoreName, v))
}

// StoreNameIn applies the In predicate on the "store_name" field.
func StoreNameIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldStoreName, vs...))
}

// StoreNameNotIn applies the NotIn predicate on the "store_name" field.
func StoreNameNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldStoreName, vs...))
}

// StoreNameGT applies the GT predicate on the "store_name" field.
func StoreNameGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldStoreName, v))
}

// StoreNameGTE applies the GTE predicate on the "store_name" field.
func StoreNameGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldStoreName, v))
}

// StoreNameLT applies the LT predicate on the "store_name" field.
func StoreNameLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldStoreName, v))
}

// StoreNameLTE applies the LTE predicate on the "store_name" field.
func StoreNameLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldStoreName, v))
}

// StoreNameContains applies the Contains predicate on the "store_name" field.
func StoreNameContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldStoreName, v))
}

// StoreNameHasPrefix applies the HasPrefix predicate on the "store_name" field.
func StoreNameHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldStoreName, v))
}

// StoreNameHasSuffix applies the HasSuffix predicate on the "store_name" field.
func StoreNameHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldStoreName, v))
}

// StoreNameEqualFold applies the EqualFold predicate on the "store_name" field.
func StoreNameEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldStoreName, v))
}

// StoreNameContainsFold applies the ContainsFold predicate on the "store_name" field.
func StoreNameContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldStoreName, v))
}

// StoreShortNameEQ applies the EQ predicate on the "store_short_name" field.
func StoreShortNameEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreShortName, v))
}

// StoreShortNameNEQ applies the NEQ predicate on the "store_short_name" field.
func StoreShortNameNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldStoreShortName, v))
}

// StoreShortNameIn applies the In predicate on the "store_short_name" field.
func StoreShortNameIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldStoreShortName, vs...))
}

// StoreShortNameNotIn applies the NotIn predicate on the "store_short_name" field.
func StoreShortNameNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldStoreShortName, vs...))
}

// StoreShortNameGT applies the GT predicate on the "store_short_name" field.
func StoreShortNameGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldStoreShortName, v))
}

// StoreShortNameGTE applies the GTE predicate on the "store_short_name" field.
func StoreShortNameGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldStoreShortName, v))
}

// StoreShortNameLT applies the LT predicate on the "store_short_name" field.
func StoreShortNameLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldStoreShortName, v))
}

// StoreShortNameLTE applies the LTE predicate on the "store_short_name" field.
func StoreShortNameLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldStoreShortName, v))
}

// StoreShortNameContains applies the Contains predicate on the "store_short_name" field.
func StoreShortNameContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldStoreShortName, v))
}

// StoreShortNameHasPrefix applies the HasPrefix predicate on the "store_short_name" field.
func StoreShortNameHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldStoreShortName, v))
}

// StoreShortNameHasSuffix applies the HasSuffix predicate on the "store_short_name" field.
func StoreShortNameHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldStoreShortName, v))
}

// StoreShortNameEqualFold applies the EqualFold predicate on the "store_short_name" field.
func StoreShortNameEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldStoreShortName, v))
}

// StoreShortNameContainsFold applies the ContainsFold predicate on the "store_short_name" field.
func StoreShortNameContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldStoreShortName, v))
}

// StoreCodeEQ applies the EQ predicate on the "store_code" field.
func StoreCodeEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreCode, v))
}

// StoreCodeNEQ applies the NEQ predicate on the "store_code" field.
func StoreCodeNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldStoreCode, v))
}

// StoreCodeIn applies the In predicate on the "store_code" field.
func StoreCodeIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldStoreCode, vs...))
}

// StoreCodeNotIn applies the NotIn predicate on the "store_code" field.
func StoreCodeNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldStoreCode, vs...))
}

// StoreCodeGT applies the GT predicate on the "store_code" field.
func StoreCodeGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldStoreCode, v))
}

// StoreCodeGTE applies the GTE predicate on the "store_code" field.
func StoreCodeGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldStoreCode, v))
}

// StoreCodeLT applies the LT predicate on the "store_code" field.
func StoreCodeLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldStoreCode, v))
}

// StoreCodeLTE applies the LTE predicate on the "store_code" field.
func StoreCodeLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldStoreCode, v))
}

// StoreCodeContains applies the Contains predicate on the "store_code" field.
func StoreCodeContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldStoreCode, v))
}

// StoreCodeHasPrefix applies the HasPrefix predicate on the "store_code" field.
func StoreCodeHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldStoreCode, v))
}

// StoreCodeHasSuffix applies the HasSuffix predicate on the "store_code" field.
func StoreCodeHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldStoreCode, v))
}

// StoreCodeEqualFold applies the EqualFold predicate on the "store_code" field.
func StoreCodeEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldStoreCode, v))
}

// StoreCodeContainsFold applies the ContainsFold predicate on the "store_code" field.
func StoreCodeContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldStoreCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v domain.StoreStatus) predicate.Store {
	vc := v
	return predicate.Store(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v domain.StoreStatus) predicate.Store {
	vc := v
	return predicate.Store(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...domain.StoreStatus) predicate.Store {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Store(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...domain.StoreStatus) predicate.Store {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Store(sql.FieldNotIn(FieldStatus, v...))
}

// BusinessModelEQ applies the EQ predicate on the "business_model" field.
func BusinessModelEQ(v domain.BusinessModel) predicate.Store {
	vc := v
	return predicate.Store(sql.FieldEQ(FieldBusinessModel, vc))
}

// BusinessModelNEQ applies the NEQ predicate on the "business_model" field.
func BusinessModelNEQ(v domain.BusinessModel) predicate.Store {
	vc := v
	return predicate.Store(sql.FieldNEQ(FieldBusinessModel, vc))
}

// BusinessModelIn applies the In predicate on the "business_model" field.
func BusinessModelIn(vs ...domain.BusinessModel) predicate.Store {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Store(sql.FieldIn(FieldBusinessModel, v...))
}

// BusinessModelNotIn applies the NotIn predicate on the "business_model" field.
func BusinessModelNotIn(vs ...domain.BusinessModel) predicate.Store {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Store(sql.FieldNotIn(FieldBusinessModel, v...))
}

// BusinessTypeIDEQ applies the EQ predicate on the "business_type_id" field.
func BusinessTypeIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldBusinessTypeID, v))
}

// BusinessTypeIDNEQ applies the NEQ predicate on the "business_type_id" field.
func BusinessTypeIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldBusinessTypeID, v))
}

// BusinessTypeIDIn applies the In predicate on the "business_type_id" field.
func BusinessTypeIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldBusinessTypeID, vs...))
}

// BusinessTypeIDNotIn applies the NotIn predicate on the "business_type_id" field.
func BusinessTypeIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldBusinessTypeID, vs...))
}

// LocationNumberEQ applies the EQ predicate on the "location_number" field.
func LocationNumberEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLocationNumber, v))
}

// LocationNumberNEQ applies the NEQ predicate on the "location_number" field.
func LocationNumberNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldLocationNumber, v))
}

// LocationNumberIn applies the In predicate on the "location_number" field.
func LocationNumberIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldLocationNumber, vs...))
}

// LocationNumberNotIn applies the NotIn predicate on the "location_number" field.
func LocationNumberNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldLocationNumber, vs...))
}

// LocationNumberGT applies the GT predicate on the "location_number" field.
func LocationNumberGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldLocationNumber, v))
}

// LocationNumberGTE applies the GTE predicate on the "location_number" field.
func LocationNumberGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldLocationNumber, v))
}

// LocationNumberLT applies the LT predicate on the "location_number" field.
func LocationNumberLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldLocationNumber, v))
}

// LocationNumberLTE applies the LTE predicate on the "location_number" field.
func LocationNumberLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldLocationNumber, v))
}

// LocationNumberContains applies the Contains predicate on the "location_number" field.
func LocationNumberContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldLocationNumber, v))
}

// LocationNumberHasPrefix applies the HasPrefix predicate on the "location_number" field.
func LocationNumberHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldLocationNumber, v))
}

// LocationNumberHasSuffix applies the HasSuffix predicate on the "location_number" field.
func LocationNumberHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldLocationNumber, v))
}

// LocationNumberEqualFold applies the EqualFold predicate on the "location_number" field.
func LocationNumberEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldLocationNumber, v))
}

// LocationNumberContainsFold applies the ContainsFold predicate on the "location_number" field.
func LocationNumberContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldLocationNumber, v))
}

// ContactNameEQ applies the EQ predicate on the "contact_name" field.
func ContactNameEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldContactName, v))
}

// ContactNameNEQ applies the NEQ predicate on the "contact_name" field.
func ContactNameNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldContactName, v))
}

// ContactNameIn applies the In predicate on the "contact_name" field.
func ContactNameIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldContactName, vs...))
}

// ContactNameNotIn applies the NotIn predicate on the "contact_name" field.
func ContactNameNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldContactName, vs...))
}

// ContactNameGT applies the GT predicate on the "contact_name" field.
func ContactNameGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldContactName, v))
}

// ContactNameGTE applies the GTE predicate on the "contact_name" field.
func ContactNameGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldContactName, v))
}

// ContactNameLT applies the LT predicate on the "contact_name" field.
func ContactNameLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldContactName, v))
}

// ContactNameLTE applies the LTE predicate on the "contact_name" field.
func ContactNameLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldContactName, v))
}

// ContactNameContains applies the Contains predicate on the "contact_name" field.
func ContactNameContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldContactName, v))
}

// ContactNameHasPrefix applies the HasPrefix predicate on the "contact_name" field.
func ContactNameHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldContactName, v))
}

// ContactNameHasSuffix applies the HasSuffix predicate on the "contact_name" field.
func ContactNameHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldContactName, v))
}

// ContactNameEqualFold applies the EqualFold predicate on the "contact_name" field.
func ContactNameEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldContactName, v))
}

// ContactNameContainsFold applies the ContainsFold predicate on the "contact_name" field.
func ContactNameContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldContactName, v))
}

// ContactPhoneEQ applies the EQ predicate on the "contact_phone" field.
func ContactPhoneEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldContactPhone, v))
}

// ContactPhoneNEQ applies the NEQ predicate on the "contact_phone" field.
func ContactPhoneNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldContactPhone, v))
}

// ContactPhoneIn applies the In predicate on the "contact_phone" field.
func ContactPhoneIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldContactPhone, vs...))
}

// ContactPhoneNotIn applies the NotIn predicate on the "contact_phone" field.
func ContactPhoneNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldContactPhone, vs...))
}

// ContactPhoneGT applies the GT predicate on the "contact_phone" field.
func ContactPhoneGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldContactPhone, v))
}

// ContactPhoneGTE applies the GTE predicate on the "contact_phone" field.
func ContactPhoneGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldContactPhone, v))
}

// ContactPhoneLT applies the LT predicate on the "contact_phone" field.
func ContactPhoneLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldContactPhone, v))
}

// ContactPhoneLTE applies the LTE predicate on the "contact_phone" field.
func ContactPhoneLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldContactPhone, v))
}

// ContactPhoneContains applies the Contains predicate on the "contact_phone" field.
func ContactPhoneContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldContactPhone, v))
}

// ContactPhoneHasPrefix applies the HasPrefix predicate on the "contact_phone" field.
func ContactPhoneHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldContactPhone, v))
}

// ContactPhoneHasSuffix applies the HasSuffix predicate on the "contact_phone" field.
func ContactPhoneHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldContactPhone, v))
}

// ContactPhoneEqualFold applies the EqualFold predicate on the "contact_phone" field.
func ContactPhoneEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldContactPhone, v))
}

// ContactPhoneContainsFold applies the ContainsFold predicate on the "contact_phone" field.
func ContactPhoneContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldContactPhone, v))
}

// UnifiedSocialCreditCodeEQ applies the EQ predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeNEQ applies the NEQ predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeIn applies the In predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldUnifiedSocialCreditCode, vs...))
}

// UnifiedSocialCreditCodeNotIn applies the NotIn predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldUnifiedSocialCreditCode, vs...))
}

// UnifiedSocialCreditCodeGT applies the GT predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeGTE applies the GTE predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeLT applies the LT predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeLTE applies the LTE predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeContains applies the Contains predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeHasPrefix applies the HasPrefix predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeHasSuffix applies the HasSuffix predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeEqualFold applies the EqualFold predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldUnifiedSocialCreditCode, v))
}

// UnifiedSocialCreditCodeContainsFold applies the ContainsFold predicate on the "unified_social_credit_code" field.
func UnifiedSocialCreditCodeContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldUnifiedSocialCreditCode, v))
}

// StoreLogoEQ applies the EQ predicate on the "store_logo" field.
func StoreLogoEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStoreLogo, v))
}

// StoreLogoNEQ applies the NEQ predicate on the "store_logo" field.
func StoreLogoNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldStoreLogo, v))
}

// StoreLogoIn applies the In predicate on the "store_logo" field.
func StoreLogoIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldStoreLogo, vs...))
}

// StoreLogoNotIn applies the NotIn predicate on the "store_logo" field.
func StoreLogoNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldStoreLogo, vs...))
}

// StoreLogoGT applies the GT predicate on the "store_logo" field.
func StoreLogoGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldStoreLogo, v))
}

// StoreLogoGTE applies the GTE predicate on the "store_logo" field.
func StoreLogoGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldStoreLogo, v))
}

// StoreLogoLT applies the LT predicate on the "store_logo" field.
func StoreLogoLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldStoreLogo, v))
}

// StoreLogoLTE applies the LTE predicate on the "store_logo" field.
func StoreLogoLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldStoreLogo, v))
}

// StoreLogoContains applies the Contains predicate on the "store_logo" field.
func StoreLogoContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldStoreLogo, v))
}

// StoreLogoHasPrefix applies the HasPrefix predicate on the "store_logo" field.
func StoreLogoHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldStoreLogo, v))
}

// StoreLogoHasSuffix applies the HasSuffix predicate on the "store_logo" field.
func StoreLogoHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldStoreLogo, v))
}

// StoreLogoEqualFold applies the EqualFold predicate on the "store_logo" field.
func StoreLogoEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldStoreLogo, v))
}

// StoreLogoContainsFold applies the ContainsFold predicate on the "store_logo" field.
func StoreLogoContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldStoreLogo, v))
}

// BusinessLicenseURLEQ applies the EQ predicate on the "business_license_url" field.
func BusinessLicenseURLEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLNEQ applies the NEQ predicate on the "business_license_url" field.
func BusinessLicenseURLNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLIn applies the In predicate on the "business_license_url" field.
func BusinessLicenseURLIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldBusinessLicenseURL, vs...))
}

// BusinessLicenseURLNotIn applies the NotIn predicate on the "business_license_url" field.
func BusinessLicenseURLNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldBusinessLicenseURL, vs...))
}

// BusinessLicenseURLGT applies the GT predicate on the "business_license_url" field.
func BusinessLicenseURLGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLGTE applies the GTE predicate on the "business_license_url" field.
func BusinessLicenseURLGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLLT applies the LT predicate on the "business_license_url" field.
func BusinessLicenseURLLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLLTE applies the LTE predicate on the "business_license_url" field.
func BusinessLicenseURLLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLContains applies the Contains predicate on the "business_license_url" field.
func BusinessLicenseURLContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLHasPrefix applies the HasPrefix predicate on the "business_license_url" field.
func BusinessLicenseURLHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLHasSuffix applies the HasSuffix predicate on the "business_license_url" field.
func BusinessLicenseURLHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLEqualFold applies the EqualFold predicate on the "business_license_url" field.
func BusinessLicenseURLEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldBusinessLicenseURL, v))
}

// BusinessLicenseURLContainsFold applies the ContainsFold predicate on the "business_license_url" field.
func BusinessLicenseURLContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldBusinessLicenseURL, v))
}

// StorefrontURLEQ applies the EQ predicate on the "storefront_url" field.
func StorefrontURLEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldStorefrontURL, v))
}

// StorefrontURLNEQ applies the NEQ predicate on the "storefront_url" field.
func StorefrontURLNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldStorefrontURL, v))
}

// StorefrontURLIn applies the In predicate on the "storefront_url" field.
func StorefrontURLIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldStorefrontURL, vs...))
}

// StorefrontURLNotIn applies the NotIn predicate on the "storefront_url" field.
func StorefrontURLNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldStorefrontURL, vs...))
}

// StorefrontURLGT applies the GT predicate on the "storefront_url" field.
func StorefrontURLGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldStorefrontURL, v))
}

// StorefrontURLGTE applies the GTE predicate on the "storefront_url" field.
func StorefrontURLGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldStorefrontURL, v))
}

// StorefrontURLLT applies the LT predicate on the "storefront_url" field.
func StorefrontURLLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldStorefrontURL, v))
}

// StorefrontURLLTE applies the LTE predicate on the "storefront_url" field.
func StorefrontURLLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldStorefrontURL, v))
}

// StorefrontURLContains applies the Contains predicate on the "storefront_url" field.
func StorefrontURLContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldStorefrontURL, v))
}

// StorefrontURLHasPrefix applies the HasPrefix predicate on the "storefront_url" field.
func StorefrontURLHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldStorefrontURL, v))
}

// StorefrontURLHasSuffix applies the HasSuffix predicate on the "storefront_url" field.
func StorefrontURLHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldStorefrontURL, v))
}

// StorefrontURLEqualFold applies the EqualFold predicate on the "storefront_url" field.
func StorefrontURLEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldStorefrontURL, v))
}

// StorefrontURLContainsFold applies the ContainsFold predicate on the "storefront_url" field.
func StorefrontURLContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldStorefrontURL, v))
}

// CashierDeskURLEQ applies the EQ predicate on the "cashier_desk_url" field.
func CashierDeskURLEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCashierDeskURL, v))
}

// CashierDeskURLNEQ applies the NEQ predicate on the "cashier_desk_url" field.
func CashierDeskURLNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldCashierDeskURL, v))
}

// CashierDeskURLIn applies the In predicate on the "cashier_desk_url" field.
func CashierDeskURLIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldCashierDeskURL, vs...))
}

// CashierDeskURLNotIn applies the NotIn predicate on the "cashier_desk_url" field.
func CashierDeskURLNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldCashierDeskURL, vs...))
}

// CashierDeskURLGT applies the GT predicate on the "cashier_desk_url" field.
func CashierDeskURLGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldCashierDeskURL, v))
}

// CashierDeskURLGTE applies the GTE predicate on the "cashier_desk_url" field.
func CashierDeskURLGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldCashierDeskURL, v))
}

// CashierDeskURLLT applies the LT predicate on the "cashier_desk_url" field.
func CashierDeskURLLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldCashierDeskURL, v))
}

// CashierDeskURLLTE applies the LTE predicate on the "cashier_desk_url" field.
func CashierDeskURLLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldCashierDeskURL, v))
}

// CashierDeskURLContains applies the Contains predicate on the "cashier_desk_url" field.
func CashierDeskURLContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldCashierDeskURL, v))
}

// CashierDeskURLHasPrefix applies the HasPrefix predicate on the "cashier_desk_url" field.
func CashierDeskURLHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldCashierDeskURL, v))
}

// CashierDeskURLHasSuffix applies the HasSuffix predicate on the "cashier_desk_url" field.
func CashierDeskURLHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldCashierDeskURL, v))
}

// CashierDeskURLEqualFold applies the EqualFold predicate on the "cashier_desk_url" field.
func CashierDeskURLEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldCashierDeskURL, v))
}

// CashierDeskURLContainsFold applies the ContainsFold predicate on the "cashier_desk_url" field.
func CashierDeskURLContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldCashierDeskURL, v))
}

// DiningEnvironmentURLEQ applies the EQ predicate on the "dining_environment_url" field.
func DiningEnvironmentURLEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLNEQ applies the NEQ predicate on the "dining_environment_url" field.
func DiningEnvironmentURLNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLIn applies the In predicate on the "dining_environment_url" field.
func DiningEnvironmentURLIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldDiningEnvironmentURL, vs...))
}

// DiningEnvironmentURLNotIn applies the NotIn predicate on the "dining_environment_url" field.
func DiningEnvironmentURLNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldDiningEnvironmentURL, vs...))
}

// DiningEnvironmentURLGT applies the GT predicate on the "dining_environment_url" field.
func DiningEnvironmentURLGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLGTE applies the GTE predicate on the "dining_environment_url" field.
func DiningEnvironmentURLGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLLT applies the LT predicate on the "dining_environment_url" field.
func DiningEnvironmentURLLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLLTE applies the LTE predicate on the "dining_environment_url" field.
func DiningEnvironmentURLLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLContains applies the Contains predicate on the "dining_environment_url" field.
func DiningEnvironmentURLContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLHasPrefix applies the HasPrefix predicate on the "dining_environment_url" field.
func DiningEnvironmentURLHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLHasSuffix applies the HasSuffix predicate on the "dining_environment_url" field.
func DiningEnvironmentURLHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLEqualFold applies the EqualFold predicate on the "dining_environment_url" field.
func DiningEnvironmentURLEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldDiningEnvironmentURL, v))
}

// DiningEnvironmentURLContainsFold applies the ContainsFold predicate on the "dining_environment_url" field.
func DiningEnvironmentURLContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldDiningEnvironmentURL, v))
}

// FoodOperationLicenseURLEQ applies the EQ predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLNEQ applies the NEQ predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLIn applies the In predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldFoodOperationLicenseURL, vs...))
}

// FoodOperationLicenseURLNotIn applies the NotIn predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldFoodOperationLicenseURL, vs...))
}

// FoodOperationLicenseURLGT applies the GT predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLGTE applies the GTE predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLLT applies the LT predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLLTE applies the LTE predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLContains applies the Contains predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLHasPrefix applies the HasPrefix predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLHasSuffix applies the HasSuffix predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLEqualFold applies the EqualFold predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldFoodOperationLicenseURL, v))
}

// FoodOperationLicenseURLContainsFold applies the ContainsFold predicate on the "food_operation_license_url" field.
func FoodOperationLicenseURLContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldFoodOperationLicenseURL, v))
}

// CountryIDEQ applies the EQ predicate on the "country_id" field.
func CountryIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCountryID, v))
}

// CountryIDNEQ applies the NEQ predicate on the "country_id" field.
func CountryIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldCountryID, v))
}

// CountryIDIn applies the In predicate on the "country_id" field.
func CountryIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldCountryID, vs...))
}

// CountryIDNotIn applies the NotIn predicate on the "country_id" field.
func CountryIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldCountryID, vs...))
}

// CountryIDIsNil applies the IsNil predicate on the "country_id" field.
func CountryIDIsNil() predicate.Store {
	return predicate.Store(sql.FieldIsNull(FieldCountryID))
}

// CountryIDNotNil applies the NotNil predicate on the "country_id" field.
func CountryIDNotNil() predicate.Store {
	return predicate.Store(sql.FieldNotNull(FieldCountryID))
}

// ProvinceIDEQ applies the EQ predicate on the "province_id" field.
func ProvinceIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldProvinceID, v))
}

// ProvinceIDNEQ applies the NEQ predicate on the "province_id" field.
func ProvinceIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldProvinceID, v))
}

// ProvinceIDIn applies the In predicate on the "province_id" field.
func ProvinceIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldProvinceID, vs...))
}

// ProvinceIDNotIn applies the NotIn predicate on the "province_id" field.
func ProvinceIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldProvinceID, vs...))
}

// ProvinceIDIsNil applies the IsNil predicate on the "province_id" field.
func ProvinceIDIsNil() predicate.Store {
	return predicate.Store(sql.FieldIsNull(FieldProvinceID))
}

// ProvinceIDNotNil applies the NotNil predicate on the "province_id" field.
func ProvinceIDNotNil() predicate.Store {
	return predicate.Store(sql.FieldNotNull(FieldProvinceID))
}

// CityIDEQ applies the EQ predicate on the "city_id" field.
func CityIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldCityID, v))
}

// CityIDNEQ applies the NEQ predicate on the "city_id" field.
func CityIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldCityID, v))
}

// CityIDIn applies the In predicate on the "city_id" field.
func CityIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldCityID, vs...))
}

// CityIDNotIn applies the NotIn predicate on the "city_id" field.
func CityIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldCityID, vs...))
}

// CityIDIsNil applies the IsNil predicate on the "city_id" field.
func CityIDIsNil() predicate.Store {
	return predicate.Store(sql.FieldIsNull(FieldCityID))
}

// CityIDNotNil applies the NotNil predicate on the "city_id" field.
func CityIDNotNil() predicate.Store {
	return predicate.Store(sql.FieldNotNull(FieldCityID))
}

// DistrictIDEQ applies the EQ predicate on the "district_id" field.
func DistrictIDEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldDistrictID, v))
}

// DistrictIDNEQ applies the NEQ predicate on the "district_id" field.
func DistrictIDNEQ(v uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldDistrictID, v))
}

// DistrictIDIn applies the In predicate on the "district_id" field.
func DistrictIDIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldDistrictID, vs...))
}

// DistrictIDNotIn applies the NotIn predicate on the "district_id" field.
func DistrictIDNotIn(vs ...uuid.UUID) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldDistrictID, vs...))
}

// DistrictIDIsNil applies the IsNil predicate on the "district_id" field.
func DistrictIDIsNil() predicate.Store {
	return predicate.Store(sql.FieldIsNull(FieldDistrictID))
}

// DistrictIDNotNil applies the NotNil predicate on the "district_id" field.
func DistrictIDNotNil() predicate.Store {
	return predicate.Store(sql.FieldNotNull(FieldDistrictID))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldAddress, v))
}

// LngEQ applies the EQ predicate on the "lng" field.
func LngEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLng, v))
}

// LngNEQ applies the NEQ predicate on the "lng" field.
func LngNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldLng, v))
}

// LngIn applies the In predicate on the "lng" field.
func LngIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldLng, vs...))
}

// LngNotIn applies the NotIn predicate on the "lng" field.
func LngNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldLng, vs...))
}

// LngGT applies the GT predicate on the "lng" field.
func LngGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldLng, v))
}

// LngGTE applies the GTE predicate on the "lng" field.
func LngGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldLng, v))
}

// LngLT applies the LT predicate on the "lng" field.
func LngLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldLng, v))
}

// LngLTE applies the LTE predicate on the "lng" field.
func LngLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldLng, v))
}

// LngContains applies the Contains predicate on the "lng" field.
func LngContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldLng, v))
}

// LngHasPrefix applies the HasPrefix predicate on the "lng" field.
func LngHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldLng, v))
}

// LngHasSuffix applies the HasSuffix predicate on the "lng" field.
func LngHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldLng, v))
}

// LngEqualFold applies the EqualFold predicate on the "lng" field.
func LngEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldLng, v))
}

// LngContainsFold applies the ContainsFold predicate on the "lng" field.
func LngContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldLng, v))
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldLat, v))
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldLat, v))
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldLat, vs...))
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldLat, vs...))
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldLat, v))
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldLat, v))
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldLat, v))
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldLat, v))
}

// LatContains applies the Contains predicate on the "lat" field.
func LatContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldLat, v))
}

// LatHasPrefix applies the HasPrefix predicate on the "lat" field.
func LatHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldLat, v))
}

// LatHasSuffix applies the HasSuffix predicate on the "lat" field.
func LatHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldLat, v))
}

// LatEqualFold applies the EqualFold predicate on the "lat" field.
func LatEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldLat, v))
}

// LatContainsFold applies the ContainsFold predicate on the "lat" field.
func LatContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldLat, v))
}

// SuperAccountEQ applies the EQ predicate on the "super_account" field.
func SuperAccountEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldEQ(FieldSuperAccount, v))
}

// SuperAccountNEQ applies the NEQ predicate on the "super_account" field.
func SuperAccountNEQ(v string) predicate.Store {
	return predicate.Store(sql.FieldNEQ(FieldSuperAccount, v))
}

// SuperAccountIn applies the In predicate on the "super_account" field.
func SuperAccountIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldIn(FieldSuperAccount, vs...))
}

// SuperAccountNotIn applies the NotIn predicate on the "super_account" field.
func SuperAccountNotIn(vs ...string) predicate.Store {
	return predicate.Store(sql.FieldNotIn(FieldSuperAccount, vs...))
}

// SuperAccountGT applies the GT predicate on the "super_account" field.
func SuperAccountGT(v string) predicate.Store {
	return predicate.Store(sql.FieldGT(FieldSuperAccount, v))
}

// SuperAccountGTE applies the GTE predicate on the "super_account" field.
func SuperAccountGTE(v string) predicate.Store {
	return predicate.Store(sql.FieldGTE(FieldSuperAccount, v))
}

// SuperAccountLT applies the LT predicate on the "super_account" field.
func SuperAccountLT(v string) predicate.Store {
	return predicate.Store(sql.FieldLT(FieldSuperAccount, v))
}

// SuperAccountLTE applies the LTE predicate on the "super_account" field.
func SuperAccountLTE(v string) predicate.Store {
	return predicate.Store(sql.FieldLTE(FieldSuperAccount, v))
}

// SuperAccountContains applies the Contains predicate on the "super_account" field.
func SuperAccountContains(v string) predicate.Store {
	return predicate.Store(sql.FieldContains(FieldSuperAccount, v))
}

// SuperAccountHasPrefix applies the HasPrefix predicate on the "super_account" field.
func SuperAccountHasPrefix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasPrefix(FieldSuperAccount, v))
}

// SuperAccountHasSuffix applies the HasSuffix predicate on the "super_account" field.
func SuperAccountHasSuffix(v string) predicate.Store {
	return predicate.Store(sql.FieldHasSuffix(FieldSuperAccount, v))
}

// SuperAccountEqualFold applies the EqualFold predicate on the "super_account" field.
func SuperAccountEqualFold(v string) predicate.Store {
	return predicate.Store(sql.FieldEqualFold(FieldSuperAccount, v))
}

// SuperAccountContainsFold applies the ContainsFold predicate on the "super_account" field.
func SuperAccountContainsFold(v string) predicate.Store {
	return predicate.Store(sql.FieldContainsFold(FieldSuperAccount, v))
}

// HasMerchant applies the HasEdge predicate on the "merchant" edge.
func HasMerchant() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantTable, MerchantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantWith applies the HasEdge predicate on the "merchant" edge with a given conditions (other predicates).
func HasMerchantWith(preds ...predicate.Merchant) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newMerchantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMerchantBusinessType applies the HasEdge predicate on the "merchant_business_type" edge.
func HasMerchantBusinessType() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MerchantBusinessTypeTable, MerchantBusinessTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMerchantBusinessTypeWith applies the HasEdge predicate on the "merchant_business_type" edge with a given conditions (other predicates).
func HasMerchantBusinessTypeWith(preds ...predicate.MerchantBusinessType) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newMerchantBusinessTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCountry applies the HasEdge predicate on the "country" edge.
func HasCountry() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CountryTable, CountryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCountryWith applies the HasEdge predicate on the "country" edge with a given conditions (other predicates).
func HasCountryWith(preds ...predicate.Country) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newCountryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvince applies the HasEdge predicate on the "province" edge.
func HasProvince() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProvinceTable, ProvinceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProvinceWith applies the HasEdge predicate on the "province" edge with a given conditions (other predicates).
func HasProvinceWith(preds ...predicate.Province) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newProvinceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCity applies the HasEdge predicate on the "city" edge.
func HasCity() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CityTable, CityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCityWith applies the HasEdge predicate on the "city" edge with a given conditions (other predicates).
func HasCityWith(preds ...predicate.City) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newCityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDistrict applies the HasEdge predicate on the "district" edge.
func HasDistrict() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DistrictTable, DistrictColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDistrictWith applies the HasEdge predicate on the "district" edge with a given conditions (other predicates).
func HasDistrictWith(preds ...predicate.District) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newDistrictStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStoreUsers applies the HasEdge predicate on the "store_users" edge.
func HasStoreUsers() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StoreUsersTable, StoreUsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStoreUsersWith applies the HasEdge predicate on the "store_users" edge with a given conditions (other predicates).
func HasStoreUsersWith(preds ...predicate.StoreUser) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newStoreUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRemarks applies the HasEdge predicate on the "remarks" edge.
func HasRemarks() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RemarksTable, RemarksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRemarksWith applies the HasEdge predicate on the "remarks" edge with a given conditions (other predicates).
func HasRemarksWith(preds ...predicate.Remark) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newRemarksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStalls applies the HasEdge predicate on the "stalls" edge.
func HasStalls() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StallsTable, StallsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStallsWith applies the HasEdge predicate on the "stalls" edge with a given conditions (other predicates).
func HasStallsWith(preds ...predicate.Stall) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newStallsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdditionalFees applies the HasEdge predicate on the "additional_fees" edge.
func HasAdditionalFees() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdditionalFeesTable, AdditionalFeesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdditionalFeesWith applies the HasEdge predicate on the "additional_fees" edge with a given conditions (other predicates).
func HasAdditionalFeesWith(preds ...predicate.AdditionalFee) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newAdditionalFeesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTaxFees applies the HasEdge predicate on the "tax_fees" edge.
func HasTaxFees() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TaxFeesTable, TaxFeesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaxFeesWith applies the HasEdge predicate on the "tax_fees" edge with a given conditions (other predicates).
func HasTaxFeesWith(preds ...predicate.TaxFee) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newTaxFeesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevices applies the HasEdge predicate on the "devices" edge.
func HasDevices() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDevicesWith applies the HasEdge predicate on the "devices" edge with a given conditions (other predicates).
func HasDevicesWith(preds ...predicate.Device) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newDevicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMenus applies the HasEdge predicate on the "menus" edge.
func HasMenus() predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, MenusTable, MenusPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMenusWith applies the HasEdge predicate on the "menus" edge with a given conditions (other predicates).
func HasMenusWith(preds ...predicate.Menu) predicate.Store {
	return predicate.Store(func(s *sql.Selector) {
		step := newMenusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Store) predicate.Store {
	return predicate.Store(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Store) predicate.Store {
	return predicate.Store(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Store) predicate.Store {
	return predicate.Store(sql.NotPredicates(p))
}
