// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updated_at", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "username", Type: field.TypeString, Size: 100},
		{Name: "hashed_password", Type: field.TypeString},
		{Name: "nickname", Type: field.TypeString},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[3]},
			},
			{
				Name:    "adminuser_username_deleted_at",
				Unique:  true,
				Columns: []*schema.Column{AdminUsersColumns[4], AdminUsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
	}
)

func init() {
}
