// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"gitlab.jiguang.dev/pos-dine/dine/ent/menu"
	"gitlab.jiguang.dev/pos-dine/dine/ent/menuitem"
	"gitlab.jiguang.dev/pos-dine/dine/ent/product"
)

// MenuItemCreate is the builder for creating a MenuItem entity.
type MenuItemCreate struct {
	config
	mutation *MenuItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (mic *MenuItemCreate) SetCreatedAt(t time.Time) *MenuItemCreate {
	mic.mutation.SetCreatedAt(t)
	return mic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableCreatedAt(t *time.Time) *MenuItemCreate {
	if t != nil {
		mic.SetCreatedAt(*t)
	}
	return mic
}

// SetUpdatedAt sets the "updated_at" field.
func (mic *MenuItemCreate) SetUpdatedAt(t time.Time) *MenuItemCreate {
	mic.mutation.SetUpdatedAt(t)
	return mic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableUpdatedAt(t *time.Time) *MenuItemCreate {
	if t != nil {
		mic.SetUpdatedAt(*t)
	}
	return mic
}

// SetDeletedAt sets the "deleted_at" field.
func (mic *MenuItemCreate) SetDeletedAt(i int64) *MenuItemCreate {
	mic.mutation.SetDeletedAt(i)
	return mic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableDeletedAt(i *int64) *MenuItemCreate {
	if i != nil {
		mic.SetDeletedAt(*i)
	}
	return mic
}

// SetMenuID sets the "menu_id" field.
func (mic *MenuItemCreate) SetMenuID(u uuid.UUID) *MenuItemCreate {
	mic.mutation.SetMenuID(u)
	return mic
}

// SetProductID sets the "product_id" field.
func (mic *MenuItemCreate) SetProductID(u uuid.UUID) *MenuItemCreate {
	mic.mutation.SetProductID(u)
	return mic
}

// SetBasePrice sets the "base_price" field.
func (mic *MenuItemCreate) SetBasePrice(d decimal.Decimal) *MenuItemCreate {
	mic.mutation.SetBasePrice(d)
	return mic
}

// SetNillableBasePrice sets the "base_price" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableBasePrice(d *decimal.Decimal) *MenuItemCreate {
	if d != nil {
		mic.SetBasePrice(*d)
	}
	return mic
}

// SetMemberPrice sets the "member_price" field.
func (mic *MenuItemCreate) SetMemberPrice(d decimal.Decimal) *MenuItemCreate {
	mic.mutation.SetMemberPrice(d)
	return mic
}

// SetNillableMemberPrice sets the "member_price" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableMemberPrice(d *decimal.Decimal) *MenuItemCreate {
	if d != nil {
		mic.SetMemberPrice(*d)
	}
	return mic
}

// SetID sets the "id" field.
func (mic *MenuItemCreate) SetID(u uuid.UUID) *MenuItemCreate {
	mic.mutation.SetID(u)
	return mic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mic *MenuItemCreate) SetNillableID(u *uuid.UUID) *MenuItemCreate {
	if u != nil {
		mic.SetID(*u)
	}
	return mic
}

// SetMenu sets the "menu" edge to the Menu entity.
func (mic *MenuItemCreate) SetMenu(m *Menu) *MenuItemCreate {
	return mic.SetMenuID(m.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (mic *MenuItemCreate) SetProduct(p *Product) *MenuItemCreate {
	return mic.SetProductID(p.ID)
}

// Mutation returns the MenuItemMutation object of the builder.
func (mic *MenuItemCreate) Mutation() *MenuItemMutation {
	return mic.mutation
}

// Save creates the MenuItem in the database.
func (mic *MenuItemCreate) Save(ctx context.Context) (*MenuItem, error) {
	if err := mic.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mic.sqlSave, mic.mutation, mic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mic *MenuItemCreate) SaveX(ctx context.Context) *MenuItem {
	v, err := mic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mic *MenuItemCreate) Exec(ctx context.Context) error {
	_, err := mic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mic *MenuItemCreate) ExecX(ctx context.Context) {
	if err := mic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mic *MenuItemCreate) defaults() error {
	if _, ok := mic.mutation.CreatedAt(); !ok {
		if menuitem.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized menuitem.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := menuitem.DefaultCreatedAt()
		mic.mutation.SetCreatedAt(v)
	}
	if _, ok := mic.mutation.UpdatedAt(); !ok {
		if menuitem.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized menuitem.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := menuitem.DefaultUpdatedAt()
		mic.mutation.SetUpdatedAt(v)
	}
	if _, ok := mic.mutation.DeletedAt(); !ok {
		v := menuitem.DefaultDeletedAt
		mic.mutation.SetDeletedAt(v)
	}
	if _, ok := mic.mutation.ID(); !ok {
		if menuitem.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized menuitem.DefaultID (forgotten import ent/runtime?)")
		}
		v := menuitem.DefaultID()
		mic.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mic *MenuItemCreate) check() error {
	if _, ok := mic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MenuItem.created_at"`)}
	}
	if _, ok := mic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MenuItem.updated_at"`)}
	}
	if _, ok := mic.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "MenuItem.deleted_at"`)}
	}
	if _, ok := mic.mutation.MenuID(); !ok {
		return &ValidationError{Name: "menu_id", err: errors.New(`ent: missing required field "MenuItem.menu_id"`)}
	}
	if _, ok := mic.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "MenuItem.product_id"`)}
	}
	if len(mic.mutation.MenuIDs()) == 0 {
		return &ValidationError{Name: "menu", err: errors.New(`ent: missing required edge "MenuItem.menu"`)}
	}
	if len(mic.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "MenuItem.product"`)}
	}
	return nil
}

func (mic *MenuItemCreate) sqlSave(ctx context.Context) (*MenuItem, error) {
	if err := mic.check(); err != nil {
		return nil, err
	}
	_node, _spec := mic.createSpec()
	if err := sqlgraph.CreateNode(ctx, mic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mic.mutation.id = &_node.ID
	mic.mutation.done = true
	return _node, nil
}

func (mic *MenuItemCreate) createSpec() (*MenuItem, *sqlgraph.CreateSpec) {
	var (
		_node = &MenuItem{config: mic.config}
		_spec = sqlgraph.NewCreateSpec(menuitem.Table, sqlgraph.NewFieldSpec(menuitem.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = mic.conflict
	if id, ok := mic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mic.mutation.CreatedAt(); ok {
		_spec.SetField(menuitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mic.mutation.UpdatedAt(); ok {
		_spec.SetField(menuitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mic.mutation.DeletedAt(); ok {
		_spec.SetField(menuitem.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = value
	}
	if value, ok := mic.mutation.BasePrice(); ok {
		_spec.SetField(menuitem.FieldBasePrice, field.TypeOther, value)
		_node.BasePrice = &value
	}
	if value, ok := mic.mutation.MemberPrice(); ok {
		_spec.SetField(menuitem.FieldMemberPrice, field.TypeOther, value)
		_node.MemberPrice = &value
	}
	if nodes := mic.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuitem.MenuTable,
			Columns: []string{menuitem.MenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MenuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mic.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuitem.ProductTable,
			Columns: []string{menuitem.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MenuItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MenuItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (mic *MenuItemCreate) OnConflict(opts ...sql.ConflictOption) *MenuItemUpsertOne {
	mic.conflict = opts
	return &MenuItemUpsertOne{
		create: mic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mic *MenuItemCreate) OnConflictColumns(columns ...string) *MenuItemUpsertOne {
	mic.conflict = append(mic.conflict, sql.ConflictColumns(columns...))
	return &MenuItemUpsertOne{
		create: mic,
	}
}

type (
	// MenuItemUpsertOne is the builder for "upsert"-ing
	//  one MenuItem node.
	MenuItemUpsertOne struct {
		create *MenuItemCreate
	}

	// MenuItemUpsert is the "OnConflict" setter.
	MenuItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MenuItemUpsert) SetUpdatedAt(v time.Time) *MenuItemUpsert {
	u.Set(menuitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MenuItemUpsert) UpdateUpdatedAt() *MenuItemUpsert {
	u.SetExcluded(menuitem.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MenuItemUpsert) SetDeletedAt(v int64) *MenuItemUpsert {
	u.Set(menuitem.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MenuItemUpsert) UpdateDeletedAt() *MenuItemUpsert {
	u.SetExcluded(menuitem.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MenuItemUpsert) AddDeletedAt(v int64) *MenuItemUpsert {
	u.Add(menuitem.FieldDeletedAt, v)
	return u
}

// SetBasePrice sets the "base_price" field.
func (u *MenuItemUpsert) SetBasePrice(v decimal.Decimal) *MenuItemUpsert {
	u.Set(menuitem.FieldBasePrice, v)
	return u
}

// UpdateBasePrice sets the "base_price" field to the value that was provided on create.
func (u *MenuItemUpsert) UpdateBasePrice() *MenuItemUpsert {
	u.SetExcluded(menuitem.FieldBasePrice)
	return u
}

// ClearBasePrice clears the value of the "base_price" field.
func (u *MenuItemUpsert) ClearBasePrice() *MenuItemUpsert {
	u.SetNull(menuitem.FieldBasePrice)
	return u
}

// SetMemberPrice sets the "member_price" field.
func (u *MenuItemUpsert) SetMemberPrice(v decimal.Decimal) *MenuItemUpsert {
	u.Set(menuitem.FieldMemberPrice, v)
	return u
}

// UpdateMemberPrice sets the "member_price" field to the value that was provided on create.
func (u *MenuItemUpsert) UpdateMemberPrice() *MenuItemUpsert {
	u.SetExcluded(menuitem.FieldMemberPrice)
	return u
}

// ClearMemberPrice clears the value of the "member_price" field.
func (u *MenuItemUpsert) ClearMemberPrice() *MenuItemUpsert {
	u.SetNull(menuitem.FieldMemberPrice)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(menuitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MenuItemUpsertOne) UpdateNewValues() *MenuItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(menuitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(menuitem.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.MenuID(); exists {
			s.SetIgnore(menuitem.FieldMenuID)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(menuitem.FieldProductID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MenuItemUpsertOne) Ignore() *MenuItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MenuItemUpsertOne) DoNothing() *MenuItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MenuItemCreate.OnConflict
// documentation for more info.
func (u *MenuItemUpsertOne) Update(set func(*MenuItemUpsert)) *MenuItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MenuItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MenuItemUpsertOne) SetUpdatedAt(v time.Time) *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MenuItemUpsertOne) UpdateUpdatedAt() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MenuItemUpsertOne) SetDeletedAt(v int64) *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MenuItemUpsertOne) AddDeletedAt(v int64) *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MenuItemUpsertOne) UpdateDeletedAt() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetBasePrice sets the "base_price" field.
func (u *MenuItemUpsertOne) SetBasePrice(v decimal.Decimal) *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetBasePrice(v)
	})
}

// UpdateBasePrice sets the "base_price" field to the value that was provided on create.
func (u *MenuItemUpsertOne) UpdateBasePrice() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateBasePrice()
	})
}

// ClearBasePrice clears the value of the "base_price" field.
func (u *MenuItemUpsertOne) ClearBasePrice() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.ClearBasePrice()
	})
}

// SetMemberPrice sets the "member_price" field.
func (u *MenuItemUpsertOne) SetMemberPrice(v decimal.Decimal) *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetMemberPrice(v)
	})
}

// UpdateMemberPrice sets the "member_price" field to the value that was provided on create.
func (u *MenuItemUpsertOne) UpdateMemberPrice() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateMemberPrice()
	})
}

// ClearMemberPrice clears the value of the "member_price" field.
func (u *MenuItemUpsertOne) ClearMemberPrice() *MenuItemUpsertOne {
	return u.Update(func(s *MenuItemUpsert) {
		s.ClearMemberPrice()
	})
}

// Exec executes the query.
func (u *MenuItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MenuItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MenuItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MenuItemUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MenuItemUpsertOne.ID is not supported by MySQL driver. Use MenuItemUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MenuItemUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MenuItemCreateBulk is the builder for creating many MenuItem entities in bulk.
type MenuItemCreateBulk struct {
	config
	err      error
	builders []*MenuItemCreate
	conflict []sql.ConflictOption
}

// Save creates the MenuItem entities in the database.
func (micb *MenuItemCreateBulk) Save(ctx context.Context) ([]*MenuItem, error) {
	if micb.err != nil {
		return nil, micb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(micb.builders))
	nodes := make([]*MenuItem, len(micb.builders))
	mutators := make([]Mutator, len(micb.builders))
	for i := range micb.builders {
		func(i int, root context.Context) {
			builder := micb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, micb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = micb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, micb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, micb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (micb *MenuItemCreateBulk) SaveX(ctx context.Context) []*MenuItem {
	v, err := micb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (micb *MenuItemCreateBulk) Exec(ctx context.Context) error {
	_, err := micb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (micb *MenuItemCreateBulk) ExecX(ctx context.Context) {
	if err := micb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MenuItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MenuItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (micb *MenuItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *MenuItemUpsertBulk {
	micb.conflict = opts
	return &MenuItemUpsertBulk{
		create: micb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (micb *MenuItemCreateBulk) OnConflictColumns(columns ...string) *MenuItemUpsertBulk {
	micb.conflict = append(micb.conflict, sql.ConflictColumns(columns...))
	return &MenuItemUpsertBulk{
		create: micb,
	}
}

// MenuItemUpsertBulk is the builder for "upsert"-ing
// a bulk of MenuItem nodes.
type MenuItemUpsertBulk struct {
	create *MenuItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(menuitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MenuItemUpsertBulk) UpdateNewValues() *MenuItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(menuitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(menuitem.FieldCreatedAt)
			}
			if _, exists := b.mutation.MenuID(); exists {
				s.SetIgnore(menuitem.FieldMenuID)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(menuitem.FieldProductID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MenuItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MenuItemUpsertBulk) Ignore() *MenuItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MenuItemUpsertBulk) DoNothing() *MenuItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MenuItemCreateBulk.OnConflict
// documentation for more info.
func (u *MenuItemUpsertBulk) Update(set func(*MenuItemUpsert)) *MenuItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MenuItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MenuItemUpsertBulk) SetUpdatedAt(v time.Time) *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MenuItemUpsertBulk) UpdateUpdatedAt() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *MenuItemUpsertBulk) SetDeletedAt(v int64) *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *MenuItemUpsertBulk) AddDeletedAt(v int64) *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *MenuItemUpsertBulk) UpdateDeletedAt() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetBasePrice sets the "base_price" field.
func (u *MenuItemUpsertBulk) SetBasePrice(v decimal.Decimal) *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetBasePrice(v)
	})
}

// UpdateBasePrice sets the "base_price" field to the value that was provided on create.
func (u *MenuItemUpsertBulk) UpdateBasePrice() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateBasePrice()
	})
}

// ClearBasePrice clears the value of the "base_price" field.
func (u *MenuItemUpsertBulk) ClearBasePrice() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.ClearBasePrice()
	})
}

// SetMemberPrice sets the "member_price" field.
func (u *MenuItemUpsertBulk) SetMemberPrice(v decimal.Decimal) *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.SetMemberPrice(v)
	})
}

// UpdateMemberPrice sets the "member_price" field to the value that was provided on create.
func (u *MenuItemUpsertBulk) UpdateMemberPrice() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.UpdateMemberPrice()
	})
}

// ClearMemberPrice clears the value of the "member_price" field.
func (u *MenuItemUpsertBulk) ClearMemberPrice() *MenuItemUpsertBulk {
	return u.Update(func(s *MenuItemUpsert) {
		s.ClearMemberPrice()
	})
}

// Exec executes the query.
func (u *MenuItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MenuItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MenuItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MenuItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
