// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.jiguang.dev/pos-dine/dine/domain"
	"gitlab.jiguang.dev/pos-dine/dine/ent/dinetable"
	"gitlab.jiguang.dev/pos-dine/dine/ent/order"
)

// Order is the model entity for the Order schema.
type Order struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt int64 `json:"deleted_at,omitempty"`
	// 单号
	No string `json:"no,omitempty"`
	// 订单类型
	Type domain.OrderType `json:"type,omitempty"`
	// 订单来源
	Source domain.OrderSource `json:"source,omitempty"`
	// 订单状态
	Status domain.OrderStatus `json:"status,omitempty"`
	// 总价（优惠前）
	TotalPrice decimal.Decimal `json:"total_price,omitempty"`
	// 优惠金额
	Discount decimal.Decimal `json:"discount,omitempty"`
	// 实际总价（优惠后）
	RealPrice decimal.Decimal `json:"real_price,omitempty"`
	// 积分可用额度
	PointsAvailable decimal.Decimal `json:"points_available,omitempty"`
	// 已支付金额
	Paid decimal.Decimal `json:"paid,omitempty"`
	// 已退款金额
	Refunded decimal.Decimal `json:"refunded,omitempty"`
	// 支付渠道
	PaidChannels domain.OrderPaidChannels `json:"paid_channels,omitempty"`
	// 现金已支付金额
	CashPaid decimal.Decimal `json:"cash_paid,omitempty"`
	// 现金已退款金额
	CashRefunded decimal.Decimal `json:"cash_refunded,omitempty"`
	// 微信已支付金额
	WechatPaid decimal.Decimal `json:"wechat_paid,omitempty"`
	// 微信已退款金额
	WechatRefunded decimal.Decimal `json:"wechat_refunded,omitempty"`
	// 支付宝已支付金额
	AlipayPaid decimal.Decimal `json:"alipay_paid,omitempty"`
	// 支付宝已退款金额
	AlipayRefunded decimal.Decimal `json:"alipay_refunded,omitempty"`
	// 积分已支付金额
	PointsPaid decimal.Decimal `json:"points_paid,omitempty"`
	// 积分已退款金额
	PointsRefunded decimal.Decimal `json:"points_refunded,omitempty"`
	// 知心话钱包已支付金额
	PointsWalletPaid decimal.Decimal `json:"points_wallet_paid,omitempty"`
	// 知心话钱包已退款金额
	PointsWalletRefunded decimal.Decimal `json:"points_wallet_refunded,omitempty"`
	// 最后支付时间
	LastPaidAt *time.Time `json:"last_paid_at,omitempty"`
	// 完成时间
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// 会员ID
	MemberID int `json:"member_id,omitempty"`
	// 会员姓名
	MemberName string `json:"member_name,omitempty"`
	// 会员手机号
	MemberPhone string `json:"member_phone,omitempty"`
	// 门店ID
	StoreID int `json:"store_id,omitempty"`
	// 门店名称
	StoreName string `json:"store_name,omitempty"`
	// 台桌ID
	TableID *int `json:"table_id,omitempty"`
	// 台桌名称
	TableName string `json:"table_name,omitempty"`
	// 就餐人数
	PeopleNumber int `json:"people_number,omitempty"`
	// 创建人ID
	CreatorID int `json:"creator_id,omitempty"`
	// 创建人姓名
	CreatorName string `json:"creator_name,omitempty"`
	// 创建人类型
	CreatorType domain.OperatorType `json:"creator_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderQuery when eager-loading is set.
	Edges        OrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderEdges holds the relations/edges for other nodes in the graph.
type OrderEdges struct {
	// Items holds the value of the items edge.
	Items []*OrderItem `json:"items,omitempty"`
	// Logs holds the value of the logs edge.
	Logs []*OrderLog `json:"logs,omitempty"`
	// CurrentDinetable holds the value of the current_dinetable edge.
	CurrentDinetable *DineTable `json:"current_dinetable,omitempty"`
	// Dinetable holds the value of the dinetable edge.
	Dinetable *DineTable `json:"dinetable,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e OrderEdges) ItemsOrErr() ([]*OrderItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// LogsOrErr returns the Logs value or an error if the edge
// was not loaded in eager-loading.
func (e OrderEdges) LogsOrErr() ([]*OrderLog, error) {
	if e.loadedTypes[1] {
		return e.Logs, nil
	}
	return nil, &NotLoadedError{edge: "logs"}
}

// CurrentDinetableOrErr returns the CurrentDinetable value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) CurrentDinetableOrErr() (*DineTable, error) {
	if e.CurrentDinetable != nil {
		return e.CurrentDinetable, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: dinetable.Label}
	}
	return nil, &NotLoadedError{edge: "current_dinetable"}
}

// DinetableOrErr returns the Dinetable value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderEdges) DinetableOrErr() (*DineTable, error) {
	if e.Dinetable != nil {
		return e.Dinetable, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: dinetable.Label}
	}
	return nil, &NotLoadedError{edge: "dinetable"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Order) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case order.FieldPaidChannels:
			values[i] = new([]byte)
		case order.FieldTotalPrice, order.FieldDiscount, order.FieldRealPrice, order.FieldPointsAvailable, order.FieldPaid, order.FieldRefunded, order.FieldCashPaid, order.FieldCashRefunded, order.FieldWechatPaid, order.FieldWechatRefunded, order.FieldAlipayPaid, order.FieldAlipayRefunded, order.FieldPointsPaid, order.FieldPointsRefunded, order.FieldPointsWalletPaid, order.FieldPointsWalletRefunded:
			values[i] = new(decimal.Decimal)
		case order.FieldID, order.FieldDeletedAt, order.FieldMemberID, order.FieldStoreID, order.FieldTableID, order.FieldPeopleNumber, order.FieldCreatorID:
			values[i] = new(sql.NullInt64)
		case order.FieldNo, order.FieldType, order.FieldSource, order.FieldStatus, order.FieldMemberName, order.FieldMemberPhone, order.FieldStoreName, order.FieldTableName, order.FieldCreatorName, order.FieldCreatorType:
			values[i] = new(sql.NullString)
		case order.FieldCreatedAt, order.FieldUpdatedAt, order.FieldLastPaidAt, order.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Order fields.
func (o *Order) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case order.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		case order.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				o.CreatedAt = value.Time
			}
		case order.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				o.UpdatedAt = value.Time
			}
		case order.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				o.DeletedAt = value.Int64
			}
		case order.FieldNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field no", values[i])
			} else if value.Valid {
				o.No = value.String
			}
		case order.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				o.Type = domain.OrderType(value.String)
			}
		case order.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				o.Source = domain.OrderSource(value.String)
			}
		case order.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				o.Status = domain.OrderStatus(value.String)
			}
		case order.FieldTotalPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total_price", values[i])
			} else if value != nil {
				o.TotalPrice = *value
			}
		case order.FieldDiscount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field discount", values[i])
			} else if value != nil {
				o.Discount = *value
			}
		case order.FieldRealPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field real_price", values[i])
			} else if value != nil {
				o.RealPrice = *value
			}
		case order.FieldPointsAvailable:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field points_available", values[i])
			} else if value != nil {
				o.PointsAvailable = *value
			}
		case order.FieldPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field paid", values[i])
			} else if value != nil {
				o.Paid = *value
			}
		case order.FieldRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field refunded", values[i])
			} else if value != nil {
				o.Refunded = *value
			}
		case order.FieldPaidChannels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field paid_channels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &o.PaidChannels); err != nil {
					return fmt.Errorf("unmarshal field paid_channels: %w", err)
				}
			}
		case order.FieldCashPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field cash_paid", values[i])
			} else if value != nil {
				o.CashPaid = *value
			}
		case order.FieldCashRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field cash_refunded", values[i])
			} else if value != nil {
				o.CashRefunded = *value
			}
		case order.FieldWechatPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field wechat_paid", values[i])
			} else if value != nil {
				o.WechatPaid = *value
			}
		case order.FieldWechatRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field wechat_refunded", values[i])
			} else if value != nil {
				o.WechatRefunded = *value
			}
		case order.FieldAlipayPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field alipay_paid", values[i])
			} else if value != nil {
				o.AlipayPaid = *value
			}
		case order.FieldAlipayRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field alipay_refunded", values[i])
			} else if value != nil {
				o.AlipayRefunded = *value
			}
		case order.FieldPointsPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field points_paid", values[i])
			} else if value != nil {
				o.PointsPaid = *value
			}
		case order.FieldPointsRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field points_refunded", values[i])
			} else if value != nil {
				o.PointsRefunded = *value
			}
		case order.FieldPointsWalletPaid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field points_wallet_paid", values[i])
			} else if value != nil {
				o.PointsWalletPaid = *value
			}
		case order.FieldPointsWalletRefunded:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field points_wallet_refunded", values[i])
			} else if value != nil {
				o.PointsWalletRefunded = *value
			}
		case order.FieldLastPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_paid_at", values[i])
			} else if value.Valid {
				o.LastPaidAt = new(time.Time)
				*o.LastPaidAt = value.Time
			}
		case order.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				o.FinishedAt = new(time.Time)
				*o.FinishedAt = value.Time
			}
		case order.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				o.MemberID = int(value.Int64)
			}
		case order.FieldMemberName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_name", values[i])
			} else if value.Valid {
				o.MemberName = value.String
			}
		case order.FieldMemberPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_phone", values[i])
			} else if value.Valid {
				o.MemberPhone = value.String
			}
		case order.FieldStoreID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field store_id", values[i])
			} else if value.Valid {
				o.StoreID = int(value.Int64)
			}
		case order.FieldStoreName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field store_name", values[i])
			} else if value.Valid {
				o.StoreName = value.String
			}
		case order.FieldTableID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field table_id", values[i])
			} else if value.Valid {
				o.TableID = new(int)
				*o.TableID = int(value.Int64)
			}
		case order.FieldTableName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field table_name", values[i])
			} else if value.Valid {
				o.TableName = value.String
			}
		case order.FieldPeopleNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field people_number", values[i])
			} else if value.Valid {
				o.PeopleNumber = int(value.Int64)
			}
		case order.FieldCreatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				o.CreatorID = int(value.Int64)
			}
		case order.FieldCreatorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_name", values[i])
			} else if value.Valid {
				o.CreatorName = value.String
			}
		case order.FieldCreatorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_type", values[i])
			} else if value.Valid {
				o.CreatorType = domain.OperatorType(value.String)
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Order.
// This includes values selected through modifiers, order, etc.
func (o *Order) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the Order entity.
func (o *Order) QueryItems() *OrderItemQuery {
	return NewOrderClient(o.config).QueryItems(o)
}

// QueryLogs queries the "logs" edge of the Order entity.
func (o *Order) QueryLogs() *OrderLogQuery {
	return NewOrderClient(o.config).QueryLogs(o)
}

// QueryCurrentDinetable queries the "current_dinetable" edge of the Order entity.
func (o *Order) QueryCurrentDinetable() *DineTableQuery {
	return NewOrderClient(o.config).QueryCurrentDinetable(o)
}

// QueryDinetable queries the "dinetable" edge of the Order entity.
func (o *Order) QueryDinetable() *DineTableQuery {
	return NewOrderClient(o.config).QueryDinetable(o)
}

// Update returns a builder for updating this Order.
// Note that you need to call Order.Unwrap() before calling this method if this Order
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Order) Update() *OrderUpdateOne {
	return NewOrderClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Order entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Order) Unwrap() *Order {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Order is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Order) String() string {
	var builder strings.Builder
	builder.WriteString("Order(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	builder.WriteString("created_at=")
	builder.WriteString(o.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(o.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", o.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("no=")
	builder.WriteString(o.No)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", o.Type))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", o.Source))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", o.Status))
	builder.WriteString(", ")
	builder.WriteString("total_price=")
	builder.WriteString(fmt.Sprintf("%v", o.TotalPrice))
	builder.WriteString(", ")
	builder.WriteString("discount=")
	builder.WriteString(fmt.Sprintf("%v", o.Discount))
	builder.WriteString(", ")
	builder.WriteString("real_price=")
	builder.WriteString(fmt.Sprintf("%v", o.RealPrice))
	builder.WriteString(", ")
	builder.WriteString("points_available=")
	builder.WriteString(fmt.Sprintf("%v", o.PointsAvailable))
	builder.WriteString(", ")
	builder.WriteString("paid=")
	builder.WriteString(fmt.Sprintf("%v", o.Paid))
	builder.WriteString(", ")
	builder.WriteString("refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.Refunded))
	builder.WriteString(", ")
	builder.WriteString("paid_channels=")
	builder.WriteString(fmt.Sprintf("%v", o.PaidChannels))
	builder.WriteString(", ")
	builder.WriteString("cash_paid=")
	builder.WriteString(fmt.Sprintf("%v", o.CashPaid))
	builder.WriteString(", ")
	builder.WriteString("cash_refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.CashRefunded))
	builder.WriteString(", ")
	builder.WriteString("wechat_paid=")
	builder.WriteString(fmt.Sprintf("%v", o.WechatPaid))
	builder.WriteString(", ")
	builder.WriteString("wechat_refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.WechatRefunded))
	builder.WriteString(", ")
	builder.WriteString("alipay_paid=")
	builder.WriteString(fmt.Sprintf("%v", o.AlipayPaid))
	builder.WriteString(", ")
	builder.WriteString("alipay_refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.AlipayRefunded))
	builder.WriteString(", ")
	builder.WriteString("points_paid=")
	builder.WriteString(fmt.Sprintf("%v", o.PointsPaid))
	builder.WriteString(", ")
	builder.WriteString("points_refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.PointsRefunded))
	builder.WriteString(", ")
	builder.WriteString("points_wallet_paid=")
	builder.WriteString(fmt.Sprintf("%v", o.PointsWalletPaid))
	builder.WriteString(", ")
	builder.WriteString("points_wallet_refunded=")
	builder.WriteString(fmt.Sprintf("%v", o.PointsWalletRefunded))
	builder.WriteString(", ")
	if v := o.LastPaidAt; v != nil {
		builder.WriteString("last_paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := o.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", o.MemberID))
	builder.WriteString(", ")
	builder.WriteString("member_name=")
	builder.WriteString(o.MemberName)
	builder.WriteString(", ")
	builder.WriteString("member_phone=")
	builder.WriteString(o.MemberPhone)
	builder.WriteString(", ")
	builder.WriteString("store_id=")
	builder.WriteString(fmt.Sprintf("%v", o.StoreID))
	builder.WriteString(", ")
	builder.WriteString("store_name=")
	builder.WriteString(o.StoreName)
	builder.WriteString(", ")
	if v := o.TableID; v != nil {
		builder.WriteString("table_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("table_name=")
	builder.WriteString(o.TableName)
	builder.WriteString(", ")
	builder.WriteString("people_number=")
	builder.WriteString(fmt.Sprintf("%v", o.PeopleNumber))
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(fmt.Sprintf("%v", o.CreatorID))
	builder.WriteString(", ")
	builder.WriteString("creator_name=")
	builder.WriteString(o.CreatorName)
	builder.WriteString(", ")
	builder.WriteString("creator_type=")
	builder.WriteString(fmt.Sprintf("%v", o.CreatorType))
	builder.WriteByte(')')
	return builder.String()
}

// Orders is a parsable slice of Order.
type Orders []*Order
