// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"gitlab.jiguang.dev/pos-dine/dine/domain"
	"gitlab.jiguang.dev/pos-dine/dine/ent/order"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrderUpdate) SetUpdatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetDeletedAt sets the "deleted_at" field.
func (ou *OrderUpdate) SetDeletedAt(i int64) *OrderUpdate {
	ou.mutation.ResetDeletedAt()
	ou.mutation.SetDeletedAt(i)
	return ou
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDeletedAt(i *int64) *OrderUpdate {
	if i != nil {
		ou.SetDeletedAt(*i)
	}
	return ou
}

// AddDeletedAt adds i to the "deleted_at" field.
func (ou *OrderUpdate) AddDeletedAt(i int64) *OrderUpdate {
	ou.mutation.AddDeletedAt(i)
	return ou
}

// SetBusinessDate sets the "business_date" field.
func (ou *OrderUpdate) SetBusinessDate(s string) *OrderUpdate {
	ou.mutation.SetBusinessDate(s)
	return ou
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableBusinessDate(s *string) *OrderUpdate {
	if s != nil {
		ou.SetBusinessDate(*s)
	}
	return ou
}

// SetShiftNo sets the "shift_no" field.
func (ou *OrderUpdate) SetShiftNo(s string) *OrderUpdate {
	ou.mutation.SetShiftNo(s)
	return ou
}

// SetNillableShiftNo sets the "shift_no" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableShiftNo(s *string) *OrderUpdate {
	if s != nil {
		ou.SetShiftNo(*s)
	}
	return ou
}

// ClearShiftNo clears the value of the "shift_no" field.
func (ou *OrderUpdate) ClearShiftNo() *OrderUpdate {
	ou.mutation.ClearShiftNo()
	return ou
}

// SetOrderNo sets the "order_no" field.
func (ou *OrderUpdate) SetOrderNo(s string) *OrderUpdate {
	ou.mutation.SetOrderNo(s)
	return ou
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderNo(s *string) *OrderUpdate {
	if s != nil {
		ou.SetOrderNo(*s)
	}
	return ou
}

// SetOrderType sets the "order_type" field.
func (ou *OrderUpdate) SetOrderType(dt domain.OrderType) *OrderUpdate {
	ou.mutation.SetOrderType(dt)
	return ou
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderType(dt *domain.OrderType) *OrderUpdate {
	if dt != nil {
		ou.SetOrderType(*dt)
	}
	return ou
}

// SetOriginOrderID sets the "origin_order_id" field.
func (ou *OrderUpdate) SetOriginOrderID(s string) *OrderUpdate {
	ou.mutation.SetOriginOrderID(s)
	return ou
}

// SetNillableOriginOrderID sets the "origin_order_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOriginOrderID(s *string) *OrderUpdate {
	if s != nil {
		ou.SetOriginOrderID(*s)
	}
	return ou
}

// ClearOriginOrderID clears the value of the "origin_order_id" field.
func (ou *OrderUpdate) ClearOriginOrderID() *OrderUpdate {
	ou.mutation.ClearOriginOrderID()
	return ou
}

// SetRefund sets the "refund" field.
func (ou *OrderUpdate) SetRefund(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetRefund(jm)
	return ou
}

// AppendRefund appends jm to the "refund" field.
func (ou *OrderUpdate) AppendRefund(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendRefund(jm)
	return ou
}

// ClearRefund clears the value of the "refund" field.
func (ou *OrderUpdate) ClearRefund() *OrderUpdate {
	ou.mutation.ClearRefund()
	return ou
}

// SetOpenedAt sets the "opened_at" field.
func (ou *OrderUpdate) SetOpenedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetOpenedAt(t)
	return ou
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOpenedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetOpenedAt(*t)
	}
	return ou
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (ou *OrderUpdate) ClearOpenedAt() *OrderUpdate {
	ou.mutation.ClearOpenedAt()
	return ou
}

// SetPlacedAt sets the "placed_at" field.
func (ou *OrderUpdate) SetPlacedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetPlacedAt(t)
	return ou
}

// SetNillablePlacedAt sets the "placed_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePlacedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetPlacedAt(*t)
	}
	return ou
}

// ClearPlacedAt clears the value of the "placed_at" field.
func (ou *OrderUpdate) ClearPlacedAt() *OrderUpdate {
	ou.mutation.ClearPlacedAt()
	return ou
}

// SetPaidAt sets the "paid_at" field.
func (ou *OrderUpdate) SetPaidAt(t time.Time) *OrderUpdate {
	ou.mutation.SetPaidAt(t)
	return ou
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePaidAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetPaidAt(*t)
	}
	return ou
}

// ClearPaidAt clears the value of the "paid_at" field.
func (ou *OrderUpdate) ClearPaidAt() *OrderUpdate {
	ou.mutation.ClearPaidAt()
	return ou
}

// SetCompletedAt sets the "completed_at" field.
func (ou *OrderUpdate) SetCompletedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetCompletedAt(t)
	return ou
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCompletedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetCompletedAt(*t)
	}
	return ou
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (ou *OrderUpdate) ClearCompletedAt() *OrderUpdate {
	ou.mutation.ClearCompletedAt()
	return ou
}

// SetOpenedBy sets the "opened_by" field.
func (ou *OrderUpdate) SetOpenedBy(s string) *OrderUpdate {
	ou.mutation.SetOpenedBy(s)
	return ou
}

// SetNillableOpenedBy sets the "opened_by" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOpenedBy(s *string) *OrderUpdate {
	if s != nil {
		ou.SetOpenedBy(*s)
	}
	return ou
}

// ClearOpenedBy clears the value of the "opened_by" field.
func (ou *OrderUpdate) ClearOpenedBy() *OrderUpdate {
	ou.mutation.ClearOpenedBy()
	return ou
}

// SetPlacedBy sets the "placed_by" field.
func (ou *OrderUpdate) SetPlacedBy(s string) *OrderUpdate {
	ou.mutation.SetPlacedBy(s)
	return ou
}

// SetNillablePlacedBy sets the "placed_by" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePlacedBy(s *string) *OrderUpdate {
	if s != nil {
		ou.SetPlacedBy(*s)
	}
	return ou
}

// ClearPlacedBy clears the value of the "placed_by" field.
func (ou *OrderUpdate) ClearPlacedBy() *OrderUpdate {
	ou.mutation.ClearPlacedBy()
	return ou
}

// SetPaidBy sets the "paid_by" field.
func (ou *OrderUpdate) SetPaidBy(s string) *OrderUpdate {
	ou.mutation.SetPaidBy(s)
	return ou
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePaidBy(s *string) *OrderUpdate {
	if s != nil {
		ou.SetPaidBy(*s)
	}
	return ou
}

// ClearPaidBy clears the value of the "paid_by" field.
func (ou *OrderUpdate) ClearPaidBy() *OrderUpdate {
	ou.mutation.ClearPaidBy()
	return ou
}

// SetDiningMode sets the "dining_mode" field.
func (ou *OrderUpdate) SetDiningMode(dm domain.DiningMode) *OrderUpdate {
	ou.mutation.SetDiningMode(dm)
	return ou
}

// SetNillableDiningMode sets the "dining_mode" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDiningMode(dm *domain.DiningMode) *OrderUpdate {
	if dm != nil {
		ou.SetDiningMode(*dm)
	}
	return ou
}

// SetOrderStatus sets the "order_status" field.
func (ou *OrderUpdate) SetOrderStatus(ds domain.OrderStatus) *OrderUpdate {
	ou.mutation.SetOrderStatus(ds)
	return ou
}

// SetNillableOrderStatus sets the "order_status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderStatus(ds *domain.OrderStatus) *OrderUpdate {
	if ds != nil {
		ou.SetOrderStatus(*ds)
	}
	return ou
}

// SetPaymentStatus sets the "payment_status" field.
func (ou *OrderUpdate) SetPaymentStatus(ds domain.PaymentStatus) *OrderUpdate {
	ou.mutation.SetPaymentStatus(ds)
	return ou
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePaymentStatus(ds *domain.PaymentStatus) *OrderUpdate {
	if ds != nil {
		ou.SetPaymentStatus(*ds)
	}
	return ou
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (ou *OrderUpdate) SetFulfillmentStatus(ds domain.FulfillmentStatus) *OrderUpdate {
	ou.mutation.SetFulfillmentStatus(ds)
	return ou
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableFulfillmentStatus(ds *domain.FulfillmentStatus) *OrderUpdate {
	if ds != nil {
		ou.SetFulfillmentStatus(*ds)
	}
	return ou
}

// ClearFulfillmentStatus clears the value of the "fulfillment_status" field.
func (ou *OrderUpdate) ClearFulfillmentStatus() *OrderUpdate {
	ou.mutation.ClearFulfillmentStatus()
	return ou
}

// SetTableStatus sets the "table_status" field.
func (ou *OrderUpdate) SetTableStatus(ds domain.TableStatus) *OrderUpdate {
	ou.mutation.SetTableStatus(ds)
	return ou
}

// SetNillableTableStatus sets the "table_status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableTableStatus(ds *domain.TableStatus) *OrderUpdate {
	if ds != nil {
		ou.SetTableStatus(*ds)
	}
	return ou
}

// ClearTableStatus clears the value of the "table_status" field.
func (ou *OrderUpdate) ClearTableStatus() *OrderUpdate {
	ou.mutation.ClearTableStatus()
	return ou
}

// SetTableID sets the "table_id" field.
func (ou *OrderUpdate) SetTableID(s string) *OrderUpdate {
	ou.mutation.SetTableID(s)
	return ou
}

// SetNillableTableID sets the "table_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableTableID(s *string) *OrderUpdate {
	if s != nil {
		ou.SetTableID(*s)
	}
	return ou
}

// ClearTableID clears the value of the "table_id" field.
func (ou *OrderUpdate) ClearTableID() *OrderUpdate {
	ou.mutation.ClearTableID()
	return ou
}

// SetTableName sets the "table_name" field.
func (ou *OrderUpdate) SetTableName(s string) *OrderUpdate {
	ou.mutation.SetTableName(s)
	return ou
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableTableName(s *string) *OrderUpdate {
	if s != nil {
		ou.SetTableName(*s)
	}
	return ou
}

// ClearTableName clears the value of the "table_name" field.
func (ou *OrderUpdate) ClearTableName() *OrderUpdate {
	ou.mutation.ClearTableName()
	return ou
}

// SetTableCapacity sets the "table_capacity" field.
func (ou *OrderUpdate) SetTableCapacity(i int) *OrderUpdate {
	ou.mutation.ResetTableCapacity()
	ou.mutation.SetTableCapacity(i)
	return ou
}

// SetNillableTableCapacity sets the "table_capacity" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableTableCapacity(i *int) *OrderUpdate {
	if i != nil {
		ou.SetTableCapacity(*i)
	}
	return ou
}

// AddTableCapacity adds i to the "table_capacity" field.
func (ou *OrderUpdate) AddTableCapacity(i int) *OrderUpdate {
	ou.mutation.AddTableCapacity(i)
	return ou
}

// ClearTableCapacity clears the value of the "table_capacity" field.
func (ou *OrderUpdate) ClearTableCapacity() *OrderUpdate {
	ou.mutation.ClearTableCapacity()
	return ou
}

// SetGuestCount sets the "guest_count" field.
func (ou *OrderUpdate) SetGuestCount(i int) *OrderUpdate {
	ou.mutation.ResetGuestCount()
	ou.mutation.SetGuestCount(i)
	return ou
}

// SetNillableGuestCount sets the "guest_count" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableGuestCount(i *int) *OrderUpdate {
	if i != nil {
		ou.SetGuestCount(*i)
	}
	return ou
}

// AddGuestCount adds i to the "guest_count" field.
func (ou *OrderUpdate) AddGuestCount(i int) *OrderUpdate {
	ou.mutation.AddGuestCount(i)
	return ou
}

// ClearGuestCount clears the value of the "guest_count" field.
func (ou *OrderUpdate) ClearGuestCount() *OrderUpdate {
	ou.mutation.ClearGuestCount()
	return ou
}

// SetMergedToOrderID sets the "merged_to_order_id" field.
func (ou *OrderUpdate) SetMergedToOrderID(s string) *OrderUpdate {
	ou.mutation.SetMergedToOrderID(s)
	return ou
}

// SetNillableMergedToOrderID sets the "merged_to_order_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableMergedToOrderID(s *string) *OrderUpdate {
	if s != nil {
		ou.SetMergedToOrderID(*s)
	}
	return ou
}

// ClearMergedToOrderID clears the value of the "merged_to_order_id" field.
func (ou *OrderUpdate) ClearMergedToOrderID() *OrderUpdate {
	ou.mutation.ClearMergedToOrderID()
	return ou
}

// SetMergedAt sets the "merged_at" field.
func (ou *OrderUpdate) SetMergedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetMergedAt(t)
	return ou
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableMergedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetMergedAt(*t)
	}
	return ou
}

// ClearMergedAt clears the value of the "merged_at" field.
func (ou *OrderUpdate) ClearMergedAt() *OrderUpdate {
	ou.mutation.ClearMergedAt()
	return ou
}

// SetStore sets the "store" field.
func (ou *OrderUpdate) SetStore(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetStore(jm)
	return ou
}

// AppendStore appends jm to the "store" field.
func (ou *OrderUpdate) AppendStore(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendStore(jm)
	return ou
}

// SetChannel sets the "channel" field.
func (ou *OrderUpdate) SetChannel(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetChannel(jm)
	return ou
}

// AppendChannel appends jm to the "channel" field.
func (ou *OrderUpdate) AppendChannel(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendChannel(jm)
	return ou
}

// SetPos sets the "pos" field.
func (ou *OrderUpdate) SetPos(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetPos(jm)
	return ou
}

// AppendPos appends jm to the "pos" field.
func (ou *OrderUpdate) AppendPos(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendPos(jm)
	return ou
}

// SetCashier sets the "cashier" field.
func (ou *OrderUpdate) SetCashier(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetCashier(jm)
	return ou
}

// AppendCashier appends jm to the "cashier" field.
func (ou *OrderUpdate) AppendCashier(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendCashier(jm)
	return ou
}

// SetMember sets the "member" field.
func (ou *OrderUpdate) SetMember(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetMember(jm)
	return ou
}

// AppendMember appends jm to the "member" field.
func (ou *OrderUpdate) AppendMember(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendMember(jm)
	return ou
}

// ClearMember clears the value of the "member" field.
func (ou *OrderUpdate) ClearMember() *OrderUpdate {
	ou.mutation.ClearMember()
	return ou
}

// SetTakeaway sets the "takeaway" field.
func (ou *OrderUpdate) SetTakeaway(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetTakeaway(jm)
	return ou
}

// AppendTakeaway appends jm to the "takeaway" field.
func (ou *OrderUpdate) AppendTakeaway(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendTakeaway(jm)
	return ou
}

// ClearTakeaway clears the value of the "takeaway" field.
func (ou *OrderUpdate) ClearTakeaway() *OrderUpdate {
	ou.mutation.ClearTakeaway()
	return ou
}

// SetCart sets the "cart" field.
func (ou *OrderUpdate) SetCart(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetCart(jm)
	return ou
}

// AppendCart appends jm to the "cart" field.
func (ou *OrderUpdate) AppendCart(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendCart(jm)
	return ou
}

// SetProducts sets the "products" field.
func (ou *OrderUpdate) SetProducts(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetProducts(jm)
	return ou
}

// AppendProducts appends jm to the "products" field.
func (ou *OrderUpdate) AppendProducts(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendProducts(jm)
	return ou
}

// SetPromotions sets the "promotions" field.
func (ou *OrderUpdate) SetPromotions(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetPromotions(jm)
	return ou
}

// AppendPromotions appends jm to the "promotions" field.
func (ou *OrderUpdate) AppendPromotions(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendPromotions(jm)
	return ou
}

// ClearPromotions clears the value of the "promotions" field.
func (ou *OrderUpdate) ClearPromotions() *OrderUpdate {
	ou.mutation.ClearPromotions()
	return ou
}

// SetCoupons sets the "coupons" field.
func (ou *OrderUpdate) SetCoupons(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetCoupons(jm)
	return ou
}

// AppendCoupons appends jm to the "coupons" field.
func (ou *OrderUpdate) AppendCoupons(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendCoupons(jm)
	return ou
}

// ClearCoupons clears the value of the "coupons" field.
func (ou *OrderUpdate) ClearCoupons() *OrderUpdate {
	ou.mutation.ClearCoupons()
	return ou
}

// SetTaxRates sets the "tax_rates" field.
func (ou *OrderUpdate) SetTaxRates(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetTaxRates(jm)
	return ou
}

// AppendTaxRates appends jm to the "tax_rates" field.
func (ou *OrderUpdate) AppendTaxRates(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendTaxRates(jm)
	return ou
}

// ClearTaxRates clears the value of the "tax_rates" field.
func (ou *OrderUpdate) ClearTaxRates() *OrderUpdate {
	ou.mutation.ClearTaxRates()
	return ou
}

// SetFees sets the "fees" field.
func (ou *OrderUpdate) SetFees(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetFees(jm)
	return ou
}

// AppendFees appends jm to the "fees" field.
func (ou *OrderUpdate) AppendFees(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendFees(jm)
	return ou
}

// ClearFees clears the value of the "fees" field.
func (ou *OrderUpdate) ClearFees() *OrderUpdate {
	ou.mutation.ClearFees()
	return ou
}

// SetPayments sets the "payments" field.
func (ou *OrderUpdate) SetPayments(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetPayments(jm)
	return ou
}

// AppendPayments appends jm to the "payments" field.
func (ou *OrderUpdate) AppendPayments(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendPayments(jm)
	return ou
}

// ClearPayments clears the value of the "payments" field.
func (ou *OrderUpdate) ClearPayments() *OrderUpdate {
	ou.mutation.ClearPayments()
	return ou
}

// SetRefundsProducts sets the "refunds_products" field.
func (ou *OrderUpdate) SetRefundsProducts(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetRefundsProducts(jm)
	return ou
}

// AppendRefundsProducts appends jm to the "refunds_products" field.
func (ou *OrderUpdate) AppendRefundsProducts(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendRefundsProducts(jm)
	return ou
}

// ClearRefundsProducts clears the value of the "refunds_products" field.
func (ou *OrderUpdate) ClearRefundsProducts() *OrderUpdate {
	ou.mutation.ClearRefundsProducts()
	return ou
}

// SetAmount sets the "amount" field.
func (ou *OrderUpdate) SetAmount(jm json.RawMessage) *OrderUpdate {
	ou.mutation.SetAmount(jm)
	return ou
}

// AppendAmount appends jm to the "amount" field.
func (ou *OrderUpdate) AppendAmount(jm json.RawMessage) *OrderUpdate {
	ou.mutation.AppendAmount(jm)
	return ou
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	if err := ou.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() error {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.BusinessDate(); ok {
		if err := order.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "Order.business_date": %w`, err)}
		}
	}
	if v, ok := ou.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := ou.mutation.OrderType(); ok {
		if err := order.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "Order.order_type": %w`, err)}
		}
	}
	if v, ok := ou.mutation.DiningMode(); ok {
		if err := order.DiningModeValidator(v); err != nil {
			return &ValidationError{Name: "dining_mode", err: fmt.Errorf(`ent: validator failed for field "Order.dining_mode": %w`, err)}
		}
	}
	if v, ok := ou.mutation.OrderStatus(); ok {
		if err := order.OrderStatusValidator(v); err != nil {
			return &ValidationError{Name: "order_status", err: fmt.Errorf(`ent: validator failed for field "Order.order_status": %w`, err)}
		}
	}
	if v, ok := ou.mutation.PaymentStatus(); ok {
		if err := order.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "Order.payment_status": %w`, err)}
		}
	}
	if v, ok := ou.mutation.FulfillmentStatus(); ok {
		if err := order.FulfillmentStatusValidator(v); err != nil {
			return &ValidationError{Name: "fulfillment_status", err: fmt.Errorf(`ent: validator failed for field "Order.fulfillment_status": %w`, err)}
		}
	}
	if v, ok := ou.mutation.TableStatus(); ok {
		if err := order.TableStatusValidator(v); err != nil {
			return &ValidationError{Name: "table_status", err: fmt.Errorf(`ent: validator failed for field "Order.table_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ou *OrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdate {
	ou.modifiers = append(ou.modifiers, modifiers...)
	return ou
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.AddedDeletedAt(); ok {
		_spec.AddField(order.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := ou.mutation.BusinessDate(); ok {
		_spec.SetField(order.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := ou.mutation.ShiftNo(); ok {
		_spec.SetField(order.FieldShiftNo, field.TypeString, value)
	}
	if ou.mutation.ShiftNoCleared() {
		_spec.ClearField(order.FieldShiftNo, field.TypeString)
	}
	if value, ok := ou.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := ou.mutation.OrderType(); ok {
		_spec.SetField(order.FieldOrderType, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.OriginOrderID(); ok {
		_spec.SetField(order.FieldOriginOrderID, field.TypeString, value)
	}
	if ou.mutation.OriginOrderIDCleared() {
		_spec.ClearField(order.FieldOriginOrderID, field.TypeString)
	}
	if value, ok := ou.mutation.Refund(); ok {
		_spec.SetField(order.FieldRefund, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedRefund(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldRefund, value)
		})
	}
	if ou.mutation.RefundCleared() {
		_spec.ClearField(order.FieldRefund, field.TypeJSON)
	}
	if value, ok := ou.mutation.OpenedAt(); ok {
		_spec.SetField(order.FieldOpenedAt, field.TypeTime, value)
	}
	if ou.mutation.OpenedAtCleared() {
		_spec.ClearField(order.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.PlacedAt(); ok {
		_spec.SetField(order.FieldPlacedAt, field.TypeTime, value)
	}
	if ou.mutation.PlacedAtCleared() {
		_spec.ClearField(order.FieldPlacedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if ou.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := ou.mutation.CompletedAt(); ok {
		_spec.SetField(order.FieldCompletedAt, field.TypeTime, value)
	}
	if ou.mutation.CompletedAtCleared() {
		_spec.ClearField(order.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.OpenedBy(); ok {
		_spec.SetField(order.FieldOpenedBy, field.TypeString, value)
	}
	if ou.mutation.OpenedByCleared() {
		_spec.ClearField(order.FieldOpenedBy, field.TypeString)
	}
	if value, ok := ou.mutation.PlacedBy(); ok {
		_spec.SetField(order.FieldPlacedBy, field.TypeString, value)
	}
	if ou.mutation.PlacedByCleared() {
		_spec.ClearField(order.FieldPlacedBy, field.TypeString)
	}
	if value, ok := ou.mutation.PaidBy(); ok {
		_spec.SetField(order.FieldPaidBy, field.TypeString, value)
	}
	if ou.mutation.PaidByCleared() {
		_spec.ClearField(order.FieldPaidBy, field.TypeString)
	}
	if value, ok := ou.mutation.DiningMode(); ok {
		_spec.SetField(order.FieldDiningMode, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.OrderStatus(); ok {
		_spec.SetField(order.FieldOrderStatus, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.PaymentStatus(); ok {
		_spec.SetField(order.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.FulfillmentStatus(); ok {
		_spec.SetField(order.FieldFulfillmentStatus, field.TypeEnum, value)
	}
	if ou.mutation.FulfillmentStatusCleared() {
		_spec.ClearField(order.FieldFulfillmentStatus, field.TypeEnum)
	}
	if value, ok := ou.mutation.TableStatus(); ok {
		_spec.SetField(order.FieldTableStatus, field.TypeEnum, value)
	}
	if ou.mutation.TableStatusCleared() {
		_spec.ClearField(order.FieldTableStatus, field.TypeEnum)
	}
	if value, ok := ou.mutation.TableID(); ok {
		_spec.SetField(order.FieldTableID, field.TypeString, value)
	}
	if ou.mutation.TableIDCleared() {
		_spec.ClearField(order.FieldTableID, field.TypeString)
	}
	if value, ok := ou.mutation.TableName(); ok {
		_spec.SetField(order.FieldTableName, field.TypeString, value)
	}
	if ou.mutation.TableNameCleared() {
		_spec.ClearField(order.FieldTableName, field.TypeString)
	}
	if value, ok := ou.mutation.TableCapacity(); ok {
		_spec.SetField(order.FieldTableCapacity, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedTableCapacity(); ok {
		_spec.AddField(order.FieldTableCapacity, field.TypeInt, value)
	}
	if ou.mutation.TableCapacityCleared() {
		_spec.ClearField(order.FieldTableCapacity, field.TypeInt)
	}
	if value, ok := ou.mutation.GuestCount(); ok {
		_spec.SetField(order.FieldGuestCount, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedGuestCount(); ok {
		_spec.AddField(order.FieldGuestCount, field.TypeInt, value)
	}
	if ou.mutation.GuestCountCleared() {
		_spec.ClearField(order.FieldGuestCount, field.TypeInt)
	}
	if value, ok := ou.mutation.MergedToOrderID(); ok {
		_spec.SetField(order.FieldMergedToOrderID, field.TypeString, value)
	}
	if ou.mutation.MergedToOrderIDCleared() {
		_spec.ClearField(order.FieldMergedToOrderID, field.TypeString)
	}
	if value, ok := ou.mutation.MergedAt(); ok {
		_spec.SetField(order.FieldMergedAt, field.TypeTime, value)
	}
	if ou.mutation.MergedAtCleared() {
		_spec.ClearField(order.FieldMergedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.Store(); ok {
		_spec.SetField(order.FieldStore, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedStore(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldStore, value)
		})
	}
	if value, ok := ou.mutation.Channel(); ok {
		_spec.SetField(order.FieldChannel, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedChannel(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldChannel, value)
		})
	}
	if value, ok := ou.mutation.Pos(); ok {
		_spec.SetField(order.FieldPos, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedPos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPos, value)
		})
	}
	if value, ok := ou.mutation.Cashier(); ok {
		_spec.SetField(order.FieldCashier, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedCashier(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCashier, value)
		})
	}
	if value, ok := ou.mutation.Member(); ok {
		_spec.SetField(order.FieldMember, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedMember(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldMember, value)
		})
	}
	if ou.mutation.MemberCleared() {
		_spec.ClearField(order.FieldMember, field.TypeJSON)
	}
	if value, ok := ou.mutation.Takeaway(); ok {
		_spec.SetField(order.FieldTakeaway, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedTakeaway(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldTakeaway, value)
		})
	}
	if ou.mutation.TakeawayCleared() {
		_spec.ClearField(order.FieldTakeaway, field.TypeJSON)
	}
	if value, ok := ou.mutation.Cart(); ok {
		_spec.SetField(order.FieldCart, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedCart(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCart, value)
		})
	}
	if value, ok := ou.mutation.Products(); ok {
		_spec.SetField(order.FieldProducts, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldProducts, value)
		})
	}
	if value, ok := ou.mutation.Promotions(); ok {
		_spec.SetField(order.FieldPromotions, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedPromotions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPromotions, value)
		})
	}
	if ou.mutation.PromotionsCleared() {
		_spec.ClearField(order.FieldPromotions, field.TypeJSON)
	}
	if value, ok := ou.mutation.Coupons(); ok {
		_spec.SetField(order.FieldCoupons, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedCoupons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCoupons, value)
		})
	}
	if ou.mutation.CouponsCleared() {
		_spec.ClearField(order.FieldCoupons, field.TypeJSON)
	}
	if value, ok := ou.mutation.TaxRates(); ok {
		_spec.SetField(order.FieldTaxRates, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedTaxRates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldTaxRates, value)
		})
	}
	if ou.mutation.TaxRatesCleared() {
		_spec.ClearField(order.FieldTaxRates, field.TypeJSON)
	}
	if value, ok := ou.mutation.Fees(); ok {
		_spec.SetField(order.FieldFees, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedFees(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldFees, value)
		})
	}
	if ou.mutation.FeesCleared() {
		_spec.ClearField(order.FieldFees, field.TypeJSON)
	}
	if value, ok := ou.mutation.Payments(); ok {
		_spec.SetField(order.FieldPayments, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedPayments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPayments, value)
		})
	}
	if ou.mutation.PaymentsCleared() {
		_spec.ClearField(order.FieldPayments, field.TypeJSON)
	}
	if value, ok := ou.mutation.RefundsProducts(); ok {
		_spec.SetField(order.FieldRefundsProducts, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedRefundsProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldRefundsProducts, value)
		})
	}
	if ou.mutation.RefundsProductsCleared() {
		_spec.ClearField(order.FieldRefundsProducts, field.TypeJSON)
	}
	if value, ok := ou.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeJSON, value)
	}
	if value, ok := ou.mutation.AppendedAmount(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldAmount, value)
		})
	}
	_spec.AddModifiers(ou.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrderUpdateOne) SetUpdatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetDeletedAt sets the "deleted_at" field.
func (ouo *OrderUpdateOne) SetDeletedAt(i int64) *OrderUpdateOne {
	ouo.mutation.ResetDeletedAt()
	ouo.mutation.SetDeletedAt(i)
	return ouo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDeletedAt(i *int64) *OrderUpdateOne {
	if i != nil {
		ouo.SetDeletedAt(*i)
	}
	return ouo
}

// AddDeletedAt adds i to the "deleted_at" field.
func (ouo *OrderUpdateOne) AddDeletedAt(i int64) *OrderUpdateOne {
	ouo.mutation.AddDeletedAt(i)
	return ouo
}

// SetBusinessDate sets the "business_date" field.
func (ouo *OrderUpdateOne) SetBusinessDate(s string) *OrderUpdateOne {
	ouo.mutation.SetBusinessDate(s)
	return ouo
}

// SetNillableBusinessDate sets the "business_date" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableBusinessDate(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetBusinessDate(*s)
	}
	return ouo
}

// SetShiftNo sets the "shift_no" field.
func (ouo *OrderUpdateOne) SetShiftNo(s string) *OrderUpdateOne {
	ouo.mutation.SetShiftNo(s)
	return ouo
}

// SetNillableShiftNo sets the "shift_no" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableShiftNo(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetShiftNo(*s)
	}
	return ouo
}

// ClearShiftNo clears the value of the "shift_no" field.
func (ouo *OrderUpdateOne) ClearShiftNo() *OrderUpdateOne {
	ouo.mutation.ClearShiftNo()
	return ouo
}

// SetOrderNo sets the "order_no" field.
func (ouo *OrderUpdateOne) SetOrderNo(s string) *OrderUpdateOne {
	ouo.mutation.SetOrderNo(s)
	return ouo
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderNo(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetOrderNo(*s)
	}
	return ouo
}

// SetOrderType sets the "order_type" field.
func (ouo *OrderUpdateOne) SetOrderType(dt domain.OrderType) *OrderUpdateOne {
	ouo.mutation.SetOrderType(dt)
	return ouo
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderType(dt *domain.OrderType) *OrderUpdateOne {
	if dt != nil {
		ouo.SetOrderType(*dt)
	}
	return ouo
}

// SetOriginOrderID sets the "origin_order_id" field.
func (ouo *OrderUpdateOne) SetOriginOrderID(s string) *OrderUpdateOne {
	ouo.mutation.SetOriginOrderID(s)
	return ouo
}

// SetNillableOriginOrderID sets the "origin_order_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOriginOrderID(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetOriginOrderID(*s)
	}
	return ouo
}

// ClearOriginOrderID clears the value of the "origin_order_id" field.
func (ouo *OrderUpdateOne) ClearOriginOrderID() *OrderUpdateOne {
	ouo.mutation.ClearOriginOrderID()
	return ouo
}

// SetRefund sets the "refund" field.
func (ouo *OrderUpdateOne) SetRefund(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetRefund(jm)
	return ouo
}

// AppendRefund appends jm to the "refund" field.
func (ouo *OrderUpdateOne) AppendRefund(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendRefund(jm)
	return ouo
}

// ClearRefund clears the value of the "refund" field.
func (ouo *OrderUpdateOne) ClearRefund() *OrderUpdateOne {
	ouo.mutation.ClearRefund()
	return ouo
}

// SetOpenedAt sets the "opened_at" field.
func (ouo *OrderUpdateOne) SetOpenedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetOpenedAt(t)
	return ouo
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOpenedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetOpenedAt(*t)
	}
	return ouo
}

// ClearOpenedAt clears the value of the "opened_at" field.
func (ouo *OrderUpdateOne) ClearOpenedAt() *OrderUpdateOne {
	ouo.mutation.ClearOpenedAt()
	return ouo
}

// SetPlacedAt sets the "placed_at" field.
func (ouo *OrderUpdateOne) SetPlacedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetPlacedAt(t)
	return ouo
}

// SetNillablePlacedAt sets the "placed_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePlacedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetPlacedAt(*t)
	}
	return ouo
}

// ClearPlacedAt clears the value of the "placed_at" field.
func (ouo *OrderUpdateOne) ClearPlacedAt() *OrderUpdateOne {
	ouo.mutation.ClearPlacedAt()
	return ouo
}

// SetPaidAt sets the "paid_at" field.
func (ouo *OrderUpdateOne) SetPaidAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetPaidAt(t)
	return ouo
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePaidAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetPaidAt(*t)
	}
	return ouo
}

// ClearPaidAt clears the value of the "paid_at" field.
func (ouo *OrderUpdateOne) ClearPaidAt() *OrderUpdateOne {
	ouo.mutation.ClearPaidAt()
	return ouo
}

// SetCompletedAt sets the "completed_at" field.
func (ouo *OrderUpdateOne) SetCompletedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetCompletedAt(t)
	return ouo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCompletedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetCompletedAt(*t)
	}
	return ouo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (ouo *OrderUpdateOne) ClearCompletedAt() *OrderUpdateOne {
	ouo.mutation.ClearCompletedAt()
	return ouo
}

// SetOpenedBy sets the "opened_by" field.
func (ouo *OrderUpdateOne) SetOpenedBy(s string) *OrderUpdateOne {
	ouo.mutation.SetOpenedBy(s)
	return ouo
}

// SetNillableOpenedBy sets the "opened_by" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOpenedBy(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetOpenedBy(*s)
	}
	return ouo
}

// ClearOpenedBy clears the value of the "opened_by" field.
func (ouo *OrderUpdateOne) ClearOpenedBy() *OrderUpdateOne {
	ouo.mutation.ClearOpenedBy()
	return ouo
}

// SetPlacedBy sets the "placed_by" field.
func (ouo *OrderUpdateOne) SetPlacedBy(s string) *OrderUpdateOne {
	ouo.mutation.SetPlacedBy(s)
	return ouo
}

// SetNillablePlacedBy sets the "placed_by" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePlacedBy(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetPlacedBy(*s)
	}
	return ouo
}

// ClearPlacedBy clears the value of the "placed_by" field.
func (ouo *OrderUpdateOne) ClearPlacedBy() *OrderUpdateOne {
	ouo.mutation.ClearPlacedBy()
	return ouo
}

// SetPaidBy sets the "paid_by" field.
func (ouo *OrderUpdateOne) SetPaidBy(s string) *OrderUpdateOne {
	ouo.mutation.SetPaidBy(s)
	return ouo
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePaidBy(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetPaidBy(*s)
	}
	return ouo
}

// ClearPaidBy clears the value of the "paid_by" field.
func (ouo *OrderUpdateOne) ClearPaidBy() *OrderUpdateOne {
	ouo.mutation.ClearPaidBy()
	return ouo
}

// SetDiningMode sets the "dining_mode" field.
func (ouo *OrderUpdateOne) SetDiningMode(dm domain.DiningMode) *OrderUpdateOne {
	ouo.mutation.SetDiningMode(dm)
	return ouo
}

// SetNillableDiningMode sets the "dining_mode" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDiningMode(dm *domain.DiningMode) *OrderUpdateOne {
	if dm != nil {
		ouo.SetDiningMode(*dm)
	}
	return ouo
}

// SetOrderStatus sets the "order_status" field.
func (ouo *OrderUpdateOne) SetOrderStatus(ds domain.OrderStatus) *OrderUpdateOne {
	ouo.mutation.SetOrderStatus(ds)
	return ouo
}

// SetNillableOrderStatus sets the "order_status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderStatus(ds *domain.OrderStatus) *OrderUpdateOne {
	if ds != nil {
		ouo.SetOrderStatus(*ds)
	}
	return ouo
}

// SetPaymentStatus sets the "payment_status" field.
func (ouo *OrderUpdateOne) SetPaymentStatus(ds domain.PaymentStatus) *OrderUpdateOne {
	ouo.mutation.SetPaymentStatus(ds)
	return ouo
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePaymentStatus(ds *domain.PaymentStatus) *OrderUpdateOne {
	if ds != nil {
		ouo.SetPaymentStatus(*ds)
	}
	return ouo
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (ouo *OrderUpdateOne) SetFulfillmentStatus(ds domain.FulfillmentStatus) *OrderUpdateOne {
	ouo.mutation.SetFulfillmentStatus(ds)
	return ouo
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableFulfillmentStatus(ds *domain.FulfillmentStatus) *OrderUpdateOne {
	if ds != nil {
		ouo.SetFulfillmentStatus(*ds)
	}
	return ouo
}

// ClearFulfillmentStatus clears the value of the "fulfillment_status" field.
func (ouo *OrderUpdateOne) ClearFulfillmentStatus() *OrderUpdateOne {
	ouo.mutation.ClearFulfillmentStatus()
	return ouo
}

// SetTableStatus sets the "table_status" field.
func (ouo *OrderUpdateOne) SetTableStatus(ds domain.TableStatus) *OrderUpdateOne {
	ouo.mutation.SetTableStatus(ds)
	return ouo
}

// SetNillableTableStatus sets the "table_status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableTableStatus(ds *domain.TableStatus) *OrderUpdateOne {
	if ds != nil {
		ouo.SetTableStatus(*ds)
	}
	return ouo
}

// ClearTableStatus clears the value of the "table_status" field.
func (ouo *OrderUpdateOne) ClearTableStatus() *OrderUpdateOne {
	ouo.mutation.ClearTableStatus()
	return ouo
}

// SetTableID sets the "table_id" field.
func (ouo *OrderUpdateOne) SetTableID(s string) *OrderUpdateOne {
	ouo.mutation.SetTableID(s)
	return ouo
}

// SetNillableTableID sets the "table_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableTableID(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetTableID(*s)
	}
	return ouo
}

// ClearTableID clears the value of the "table_id" field.
func (ouo *OrderUpdateOne) ClearTableID() *OrderUpdateOne {
	ouo.mutation.ClearTableID()
	return ouo
}

// SetTableName sets the "table_name" field.
func (ouo *OrderUpdateOne) SetTableName(s string) *OrderUpdateOne {
	ouo.mutation.SetTableName(s)
	return ouo
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableTableName(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetTableName(*s)
	}
	return ouo
}

// ClearTableName clears the value of the "table_name" field.
func (ouo *OrderUpdateOne) ClearTableName() *OrderUpdateOne {
	ouo.mutation.ClearTableName()
	return ouo
}

// SetTableCapacity sets the "table_capacity" field.
func (ouo *OrderUpdateOne) SetTableCapacity(i int) *OrderUpdateOne {
	ouo.mutation.ResetTableCapacity()
	ouo.mutation.SetTableCapacity(i)
	return ouo
}

// SetNillableTableCapacity sets the "table_capacity" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableTableCapacity(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetTableCapacity(*i)
	}
	return ouo
}

// AddTableCapacity adds i to the "table_capacity" field.
func (ouo *OrderUpdateOne) AddTableCapacity(i int) *OrderUpdateOne {
	ouo.mutation.AddTableCapacity(i)
	return ouo
}

// ClearTableCapacity clears the value of the "table_capacity" field.
func (ouo *OrderUpdateOne) ClearTableCapacity() *OrderUpdateOne {
	ouo.mutation.ClearTableCapacity()
	return ouo
}

// SetGuestCount sets the "guest_count" field.
func (ouo *OrderUpdateOne) SetGuestCount(i int) *OrderUpdateOne {
	ouo.mutation.ResetGuestCount()
	ouo.mutation.SetGuestCount(i)
	return ouo
}

// SetNillableGuestCount sets the "guest_count" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableGuestCount(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetGuestCount(*i)
	}
	return ouo
}

// AddGuestCount adds i to the "guest_count" field.
func (ouo *OrderUpdateOne) AddGuestCount(i int) *OrderUpdateOne {
	ouo.mutation.AddGuestCount(i)
	return ouo
}

// ClearGuestCount clears the value of the "guest_count" field.
func (ouo *OrderUpdateOne) ClearGuestCount() *OrderUpdateOne {
	ouo.mutation.ClearGuestCount()
	return ouo
}

// SetMergedToOrderID sets the "merged_to_order_id" field.
func (ouo *OrderUpdateOne) SetMergedToOrderID(s string) *OrderUpdateOne {
	ouo.mutation.SetMergedToOrderID(s)
	return ouo
}

// SetNillableMergedToOrderID sets the "merged_to_order_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableMergedToOrderID(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetMergedToOrderID(*s)
	}
	return ouo
}

// ClearMergedToOrderID clears the value of the "merged_to_order_id" field.
func (ouo *OrderUpdateOne) ClearMergedToOrderID() *OrderUpdateOne {
	ouo.mutation.ClearMergedToOrderID()
	return ouo
}

// SetMergedAt sets the "merged_at" field.
func (ouo *OrderUpdateOne) SetMergedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetMergedAt(t)
	return ouo
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableMergedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetMergedAt(*t)
	}
	return ouo
}

// ClearMergedAt clears the value of the "merged_at" field.
func (ouo *OrderUpdateOne) ClearMergedAt() *OrderUpdateOne {
	ouo.mutation.ClearMergedAt()
	return ouo
}

// SetStore sets the "store" field.
func (ouo *OrderUpdateOne) SetStore(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetStore(jm)
	return ouo
}

// AppendStore appends jm to the "store" field.
func (ouo *OrderUpdateOne) AppendStore(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendStore(jm)
	return ouo
}

// SetChannel sets the "channel" field.
func (ouo *OrderUpdateOne) SetChannel(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetChannel(jm)
	return ouo
}

// AppendChannel appends jm to the "channel" field.
func (ouo *OrderUpdateOne) AppendChannel(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendChannel(jm)
	return ouo
}

// SetPos sets the "pos" field.
func (ouo *OrderUpdateOne) SetPos(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetPos(jm)
	return ouo
}

// AppendPos appends jm to the "pos" field.
func (ouo *OrderUpdateOne) AppendPos(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendPos(jm)
	return ouo
}

// SetCashier sets the "cashier" field.
func (ouo *OrderUpdateOne) SetCashier(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetCashier(jm)
	return ouo
}

// AppendCashier appends jm to the "cashier" field.
func (ouo *OrderUpdateOne) AppendCashier(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendCashier(jm)
	return ouo
}

// SetMember sets the "member" field.
func (ouo *OrderUpdateOne) SetMember(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetMember(jm)
	return ouo
}

// AppendMember appends jm to the "member" field.
func (ouo *OrderUpdateOne) AppendMember(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendMember(jm)
	return ouo
}

// ClearMember clears the value of the "member" field.
func (ouo *OrderUpdateOne) ClearMember() *OrderUpdateOne {
	ouo.mutation.ClearMember()
	return ouo
}

// SetTakeaway sets the "takeaway" field.
func (ouo *OrderUpdateOne) SetTakeaway(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetTakeaway(jm)
	return ouo
}

// AppendTakeaway appends jm to the "takeaway" field.
func (ouo *OrderUpdateOne) AppendTakeaway(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendTakeaway(jm)
	return ouo
}

// ClearTakeaway clears the value of the "takeaway" field.
func (ouo *OrderUpdateOne) ClearTakeaway() *OrderUpdateOne {
	ouo.mutation.ClearTakeaway()
	return ouo
}

// SetCart sets the "cart" field.
func (ouo *OrderUpdateOne) SetCart(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetCart(jm)
	return ouo
}

// AppendCart appends jm to the "cart" field.
func (ouo *OrderUpdateOne) AppendCart(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendCart(jm)
	return ouo
}

// SetProducts sets the "products" field.
func (ouo *OrderUpdateOne) SetProducts(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetProducts(jm)
	return ouo
}

// AppendProducts appends jm to the "products" field.
func (ouo *OrderUpdateOne) AppendProducts(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendProducts(jm)
	return ouo
}

// SetPromotions sets the "promotions" field.
func (ouo *OrderUpdateOne) SetPromotions(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetPromotions(jm)
	return ouo
}

// AppendPromotions appends jm to the "promotions" field.
func (ouo *OrderUpdateOne) AppendPromotions(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendPromotions(jm)
	return ouo
}

// ClearPromotions clears the value of the "promotions" field.
func (ouo *OrderUpdateOne) ClearPromotions() *OrderUpdateOne {
	ouo.mutation.ClearPromotions()
	return ouo
}

// SetCoupons sets the "coupons" field.
func (ouo *OrderUpdateOne) SetCoupons(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetCoupons(jm)
	return ouo
}

// AppendCoupons appends jm to the "coupons" field.
func (ouo *OrderUpdateOne) AppendCoupons(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendCoupons(jm)
	return ouo
}

// ClearCoupons clears the value of the "coupons" field.
func (ouo *OrderUpdateOne) ClearCoupons() *OrderUpdateOne {
	ouo.mutation.ClearCoupons()
	return ouo
}

// SetTaxRates sets the "tax_rates" field.
func (ouo *OrderUpdateOne) SetTaxRates(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetTaxRates(jm)
	return ouo
}

// AppendTaxRates appends jm to the "tax_rates" field.
func (ouo *OrderUpdateOne) AppendTaxRates(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendTaxRates(jm)
	return ouo
}

// ClearTaxRates clears the value of the "tax_rates" field.
func (ouo *OrderUpdateOne) ClearTaxRates() *OrderUpdateOne {
	ouo.mutation.ClearTaxRates()
	return ouo
}

// SetFees sets the "fees" field.
func (ouo *OrderUpdateOne) SetFees(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetFees(jm)
	return ouo
}

// AppendFees appends jm to the "fees" field.
func (ouo *OrderUpdateOne) AppendFees(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendFees(jm)
	return ouo
}

// ClearFees clears the value of the "fees" field.
func (ouo *OrderUpdateOne) ClearFees() *OrderUpdateOne {
	ouo.mutation.ClearFees()
	return ouo
}

// SetPayments sets the "payments" field.
func (ouo *OrderUpdateOne) SetPayments(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetPayments(jm)
	return ouo
}

// AppendPayments appends jm to the "payments" field.
func (ouo *OrderUpdateOne) AppendPayments(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendPayments(jm)
	return ouo
}

// ClearPayments clears the value of the "payments" field.
func (ouo *OrderUpdateOne) ClearPayments() *OrderUpdateOne {
	ouo.mutation.ClearPayments()
	return ouo
}

// SetRefundsProducts sets the "refunds_products" field.
func (ouo *OrderUpdateOne) SetRefundsProducts(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetRefundsProducts(jm)
	return ouo
}

// AppendRefundsProducts appends jm to the "refunds_products" field.
func (ouo *OrderUpdateOne) AppendRefundsProducts(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendRefundsProducts(jm)
	return ouo
}

// ClearRefundsProducts clears the value of the "refunds_products" field.
func (ouo *OrderUpdateOne) ClearRefundsProducts() *OrderUpdateOne {
	ouo.mutation.ClearRefundsProducts()
	return ouo
}

// SetAmount sets the "amount" field.
func (ouo *OrderUpdateOne) SetAmount(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.SetAmount(jm)
	return ouo
}

// AppendAmount appends jm to the "amount" field.
func (ouo *OrderUpdateOne) AppendAmount(jm json.RawMessage) *OrderUpdateOne {
	ouo.mutation.AppendAmount(jm)
	return ouo
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	if err := ouo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() error {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.BusinessDate(); ok {
		if err := order.BusinessDateValidator(v); err != nil {
			return &ValidationError{Name: "business_date", err: fmt.Errorf(`ent: validator failed for field "Order.business_date": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.OrderType(); ok {
		if err := order.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "Order.order_type": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.DiningMode(); ok {
		if err := order.DiningModeValidator(v); err != nil {
			return &ValidationError{Name: "dining_mode", err: fmt.Errorf(`ent: validator failed for field "Order.dining_mode": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.OrderStatus(); ok {
		if err := order.OrderStatusValidator(v); err != nil {
			return &ValidationError{Name: "order_status", err: fmt.Errorf(`ent: validator failed for field "Order.order_status": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.PaymentStatus(); ok {
		if err := order.PaymentStatusValidator(v); err != nil {
			return &ValidationError{Name: "payment_status", err: fmt.Errorf(`ent: validator failed for field "Order.payment_status": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.FulfillmentStatus(); ok {
		if err := order.FulfillmentStatusValidator(v); err != nil {
			return &ValidationError{Name: "fulfillment_status", err: fmt.Errorf(`ent: validator failed for field "Order.fulfillment_status": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.TableStatus(); ok {
		if err := order.TableStatusValidator(v); err != nil {
			return &ValidationError{Name: "table_status", err: fmt.Errorf(`ent: validator failed for field "Order.table_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ouo *OrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdateOne {
	ouo.modifiers = append(ouo.modifiers, modifiers...)
	return ouo
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.AddedDeletedAt(); ok {
		_spec.AddField(order.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := ouo.mutation.BusinessDate(); ok {
		_spec.SetField(order.FieldBusinessDate, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ShiftNo(); ok {
		_spec.SetField(order.FieldShiftNo, field.TypeString, value)
	}
	if ouo.mutation.ShiftNoCleared() {
		_spec.ClearField(order.FieldShiftNo, field.TypeString)
	}
	if value, ok := ouo.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := ouo.mutation.OrderType(); ok {
		_spec.SetField(order.FieldOrderType, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.OriginOrderID(); ok {
		_spec.SetField(order.FieldOriginOrderID, field.TypeString, value)
	}
	if ouo.mutation.OriginOrderIDCleared() {
		_spec.ClearField(order.FieldOriginOrderID, field.TypeString)
	}
	if value, ok := ouo.mutation.Refund(); ok {
		_spec.SetField(order.FieldRefund, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedRefund(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldRefund, value)
		})
	}
	if ouo.mutation.RefundCleared() {
		_spec.ClearField(order.FieldRefund, field.TypeJSON)
	}
	if value, ok := ouo.mutation.OpenedAt(); ok {
		_spec.SetField(order.FieldOpenedAt, field.TypeTime, value)
	}
	if ouo.mutation.OpenedAtCleared() {
		_spec.ClearField(order.FieldOpenedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.PlacedAt(); ok {
		_spec.SetField(order.FieldPlacedAt, field.TypeTime, value)
	}
	if ouo.mutation.PlacedAtCleared() {
		_spec.ClearField(order.FieldPlacedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if ouo.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.CompletedAt(); ok {
		_spec.SetField(order.FieldCompletedAt, field.TypeTime, value)
	}
	if ouo.mutation.CompletedAtCleared() {
		_spec.ClearField(order.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.OpenedBy(); ok {
		_spec.SetField(order.FieldOpenedBy, field.TypeString, value)
	}
	if ouo.mutation.OpenedByCleared() {
		_spec.ClearField(order.FieldOpenedBy, field.TypeString)
	}
	if value, ok := ouo.mutation.PlacedBy(); ok {
		_spec.SetField(order.FieldPlacedBy, field.TypeString, value)
	}
	if ouo.mutation.PlacedByCleared() {
		_spec.ClearField(order.FieldPlacedBy, field.TypeString)
	}
	if value, ok := ouo.mutation.PaidBy(); ok {
		_spec.SetField(order.FieldPaidBy, field.TypeString, value)
	}
	if ouo.mutation.PaidByCleared() {
		_spec.ClearField(order.FieldPaidBy, field.TypeString)
	}
	if value, ok := ouo.mutation.DiningMode(); ok {
		_spec.SetField(order.FieldDiningMode, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.OrderStatus(); ok {
		_spec.SetField(order.FieldOrderStatus, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.PaymentStatus(); ok {
		_spec.SetField(order.FieldPaymentStatus, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.FulfillmentStatus(); ok {
		_spec.SetField(order.FieldFulfillmentStatus, field.TypeEnum, value)
	}
	if ouo.mutation.FulfillmentStatusCleared() {
		_spec.ClearField(order.FieldFulfillmentStatus, field.TypeEnum)
	}
	if value, ok := ouo.mutation.TableStatus(); ok {
		_spec.SetField(order.FieldTableStatus, field.TypeEnum, value)
	}
	if ouo.mutation.TableStatusCleared() {
		_spec.ClearField(order.FieldTableStatus, field.TypeEnum)
	}
	if value, ok := ouo.mutation.TableID(); ok {
		_spec.SetField(order.FieldTableID, field.TypeString, value)
	}
	if ouo.mutation.TableIDCleared() {
		_spec.ClearField(order.FieldTableID, field.TypeString)
	}
	if value, ok := ouo.mutation.TableName(); ok {
		_spec.SetField(order.FieldTableName, field.TypeString, value)
	}
	if ouo.mutation.TableNameCleared() {
		_spec.ClearField(order.FieldTableName, field.TypeString)
	}
	if value, ok := ouo.mutation.TableCapacity(); ok {
		_spec.SetField(order.FieldTableCapacity, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedTableCapacity(); ok {
		_spec.AddField(order.FieldTableCapacity, field.TypeInt, value)
	}
	if ouo.mutation.TableCapacityCleared() {
		_spec.ClearField(order.FieldTableCapacity, field.TypeInt)
	}
	if value, ok := ouo.mutation.GuestCount(); ok {
		_spec.SetField(order.FieldGuestCount, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedGuestCount(); ok {
		_spec.AddField(order.FieldGuestCount, field.TypeInt, value)
	}
	if ouo.mutation.GuestCountCleared() {
		_spec.ClearField(order.FieldGuestCount, field.TypeInt)
	}
	if value, ok := ouo.mutation.MergedToOrderID(); ok {
		_spec.SetField(order.FieldMergedToOrderID, field.TypeString, value)
	}
	if ouo.mutation.MergedToOrderIDCleared() {
		_spec.ClearField(order.FieldMergedToOrderID, field.TypeString)
	}
	if value, ok := ouo.mutation.MergedAt(); ok {
		_spec.SetField(order.FieldMergedAt, field.TypeTime, value)
	}
	if ouo.mutation.MergedAtCleared() {
		_spec.ClearField(order.FieldMergedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.Store(); ok {
		_spec.SetField(order.FieldStore, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedStore(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldStore, value)
		})
	}
	if value, ok := ouo.mutation.Channel(); ok {
		_spec.SetField(order.FieldChannel, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedChannel(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldChannel, value)
		})
	}
	if value, ok := ouo.mutation.Pos(); ok {
		_spec.SetField(order.FieldPos, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedPos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPos, value)
		})
	}
	if value, ok := ouo.mutation.Cashier(); ok {
		_spec.SetField(order.FieldCashier, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedCashier(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCashier, value)
		})
	}
	if value, ok := ouo.mutation.Member(); ok {
		_spec.SetField(order.FieldMember, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedMember(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldMember, value)
		})
	}
	if ouo.mutation.MemberCleared() {
		_spec.ClearField(order.FieldMember, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Takeaway(); ok {
		_spec.SetField(order.FieldTakeaway, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedTakeaway(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldTakeaway, value)
		})
	}
	if ouo.mutation.TakeawayCleared() {
		_spec.ClearField(order.FieldTakeaway, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Cart(); ok {
		_spec.SetField(order.FieldCart, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedCart(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCart, value)
		})
	}
	if value, ok := ouo.mutation.Products(); ok {
		_spec.SetField(order.FieldProducts, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldProducts, value)
		})
	}
	if value, ok := ouo.mutation.Promotions(); ok {
		_spec.SetField(order.FieldPromotions, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedPromotions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPromotions, value)
		})
	}
	if ouo.mutation.PromotionsCleared() {
		_spec.ClearField(order.FieldPromotions, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Coupons(); ok {
		_spec.SetField(order.FieldCoupons, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedCoupons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldCoupons, value)
		})
	}
	if ouo.mutation.CouponsCleared() {
		_spec.ClearField(order.FieldCoupons, field.TypeJSON)
	}
	if value, ok := ouo.mutation.TaxRates(); ok {
		_spec.SetField(order.FieldTaxRates, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedTaxRates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldTaxRates, value)
		})
	}
	if ouo.mutation.TaxRatesCleared() {
		_spec.ClearField(order.FieldTaxRates, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Fees(); ok {
		_spec.SetField(order.FieldFees, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedFees(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldFees, value)
		})
	}
	if ouo.mutation.FeesCleared() {
		_spec.ClearField(order.FieldFees, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Payments(); ok {
		_spec.SetField(order.FieldPayments, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedPayments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldPayments, value)
		})
	}
	if ouo.mutation.PaymentsCleared() {
		_spec.ClearField(order.FieldPayments, field.TypeJSON)
	}
	if value, ok := ouo.mutation.RefundsProducts(); ok {
		_spec.SetField(order.FieldRefundsProducts, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedRefundsProducts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldRefundsProducts, value)
		})
	}
	if ouo.mutation.RefundsProductsCleared() {
		_spec.ClearField(order.FieldRefundsProducts, field.TypeJSON)
	}
	if value, ok := ouo.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeJSON, value)
	}
	if value, ok := ouo.mutation.AppendedAmount(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldAmount, value)
		})
	}
	_spec.AddModifiers(ouo.modifiers...)
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
