// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"gitlab.jiguang.dev/pos-dine/dine/ent/additionalfee"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
	"gitlab.jiguang.dev/pos-dine/dine/ent/product"
	"gitlab.jiguang.dev/pos-dine/dine/ent/productspec"
	"gitlab.jiguang.dev/pos-dine/dine/ent/productspecrelation"
)

// ProductSpecRelationQuery is the builder for querying ProductSpecRelation entities.
type ProductSpecRelationQuery struct {
	config
	ctx            *QueryContext
	order          []productspecrelation.OrderOption
	inters         []Interceptor
	predicates     []predicate.ProductSpecRelation
	withProduct    *ProductQuery
	withSpec       *ProductSpecQuery
	withPackingFee *AdditionalFeeQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductSpecRelationQuery builder.
func (psrq *ProductSpecRelationQuery) Where(ps ...predicate.ProductSpecRelation) *ProductSpecRelationQuery {
	psrq.predicates = append(psrq.predicates, ps...)
	return psrq
}

// Limit the number of records to be returned by this query.
func (psrq *ProductSpecRelationQuery) Limit(limit int) *ProductSpecRelationQuery {
	psrq.ctx.Limit = &limit
	return psrq
}

// Offset to start from.
func (psrq *ProductSpecRelationQuery) Offset(offset int) *ProductSpecRelationQuery {
	psrq.ctx.Offset = &offset
	return psrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (psrq *ProductSpecRelationQuery) Unique(unique bool) *ProductSpecRelationQuery {
	psrq.ctx.Unique = &unique
	return psrq
}

// Order specifies how the records should be ordered.
func (psrq *ProductSpecRelationQuery) Order(o ...productspecrelation.OrderOption) *ProductSpecRelationQuery {
	psrq.order = append(psrq.order, o...)
	return psrq
}

// QueryProduct chains the current query on the "product" edge.
func (psrq *ProductSpecRelationQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: psrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := psrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := psrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productspecrelation.Table, productspecrelation.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productspecrelation.ProductTable, productspecrelation.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(psrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpec chains the current query on the "spec" edge.
func (psrq *ProductSpecRelationQuery) QuerySpec() *ProductSpecQuery {
	query := (&ProductSpecClient{config: psrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := psrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := psrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productspecrelation.Table, productspecrelation.FieldID, selector),
			sqlgraph.To(productspec.Table, productspec.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productspecrelation.SpecTable, productspecrelation.SpecColumn),
		)
		fromU = sqlgraph.SetNeighbors(psrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPackingFee chains the current query on the "packing_fee" edge.
func (psrq *ProductSpecRelationQuery) QueryPackingFee() *AdditionalFeeQuery {
	query := (&AdditionalFeeClient{config: psrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := psrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := psrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productspecrelation.Table, productspecrelation.FieldID, selector),
			sqlgraph.To(additionalfee.Table, additionalfee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productspecrelation.PackingFeeTable, productspecrelation.PackingFeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(psrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductSpecRelation entity from the query.
// Returns a *NotFoundError when no ProductSpecRelation was found.
func (psrq *ProductSpecRelationQuery) First(ctx context.Context) (*ProductSpecRelation, error) {
	nodes, err := psrq.Limit(1).All(setContextOp(ctx, psrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productspecrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) FirstX(ctx context.Context) *ProductSpecRelation {
	node, err := psrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductSpecRelation ID from the query.
// Returns a *NotFoundError when no ProductSpecRelation ID was found.
func (psrq *ProductSpecRelationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = psrq.Limit(1).IDs(setContextOp(ctx, psrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productspecrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := psrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductSpecRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductSpecRelation entity is found.
// Returns a *NotFoundError when no ProductSpecRelation entities are found.
func (psrq *ProductSpecRelationQuery) Only(ctx context.Context) (*ProductSpecRelation, error) {
	nodes, err := psrq.Limit(2).All(setContextOp(ctx, psrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productspecrelation.Label}
	default:
		return nil, &NotSingularError{productspecrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) OnlyX(ctx context.Context) *ProductSpecRelation {
	node, err := psrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductSpecRelation ID in the query.
// Returns a *NotSingularError when more than one ProductSpecRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (psrq *ProductSpecRelationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = psrq.Limit(2).IDs(setContextOp(ctx, psrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productspecrelation.Label}
	default:
		err = &NotSingularError{productspecrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := psrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductSpecRelations.
func (psrq *ProductSpecRelationQuery) All(ctx context.Context) ([]*ProductSpecRelation, error) {
	ctx = setContextOp(ctx, psrq.ctx, ent.OpQueryAll)
	if err := psrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductSpecRelation, *ProductSpecRelationQuery]()
	return withInterceptors[[]*ProductSpecRelation](ctx, psrq, qr, psrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) AllX(ctx context.Context) []*ProductSpecRelation {
	nodes, err := psrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductSpecRelation IDs.
func (psrq *ProductSpecRelationQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if psrq.ctx.Unique == nil && psrq.path != nil {
		psrq.Unique(true)
	}
	ctx = setContextOp(ctx, psrq.ctx, ent.OpQueryIDs)
	if err = psrq.Select(productspecrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := psrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (psrq *ProductSpecRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, psrq.ctx, ent.OpQueryCount)
	if err := psrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, psrq, querierCount[*ProductSpecRelationQuery](), psrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) CountX(ctx context.Context) int {
	count, err := psrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (psrq *ProductSpecRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, psrq.ctx, ent.OpQueryExist)
	switch _, err := psrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (psrq *ProductSpecRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := psrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductSpecRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (psrq *ProductSpecRelationQuery) Clone() *ProductSpecRelationQuery {
	if psrq == nil {
		return nil
	}
	return &ProductSpecRelationQuery{
		config:         psrq.config,
		ctx:            psrq.ctx.Clone(),
		order:          append([]productspecrelation.OrderOption{}, psrq.order...),
		inters:         append([]Interceptor{}, psrq.inters...),
		predicates:     append([]predicate.ProductSpecRelation{}, psrq.predicates...),
		withProduct:    psrq.withProduct.Clone(),
		withSpec:       psrq.withSpec.Clone(),
		withPackingFee: psrq.withPackingFee.Clone(),
		// clone intermediate query.
		sql:       psrq.sql.Clone(),
		path:      psrq.path,
		modifiers: append([]func(*sql.Selector){}, psrq.modifiers...),
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (psrq *ProductSpecRelationQuery) WithProduct(opts ...func(*ProductQuery)) *ProductSpecRelationQuery {
	query := (&ProductClient{config: psrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	psrq.withProduct = query
	return psrq
}

// WithSpec tells the query-builder to eager-load the nodes that are connected to
// the "spec" edge. The optional arguments are used to configure the query builder of the edge.
func (psrq *ProductSpecRelationQuery) WithSpec(opts ...func(*ProductSpecQuery)) *ProductSpecRelationQuery {
	query := (&ProductSpecClient{config: psrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	psrq.withSpec = query
	return psrq
}

// WithPackingFee tells the query-builder to eager-load the nodes that are connected to
// the "packing_fee" edge. The optional arguments are used to configure the query builder of the edge.
func (psrq *ProductSpecRelationQuery) WithPackingFee(opts ...func(*AdditionalFeeQuery)) *ProductSpecRelationQuery {
	query := (&AdditionalFeeClient{config: psrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	psrq.withPackingFee = query
	return psrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductSpecRelation.Query().
//		GroupBy(productspecrelation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (psrq *ProductSpecRelationQuery) GroupBy(field string, fields ...string) *ProductSpecRelationGroupBy {
	psrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductSpecRelationGroupBy{build: psrq}
	grbuild.flds = &psrq.ctx.Fields
	grbuild.label = productspecrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProductSpecRelation.Query().
//		Select(productspecrelation.FieldCreatedAt).
//		Scan(ctx, &v)
func (psrq *ProductSpecRelationQuery) Select(fields ...string) *ProductSpecRelationSelect {
	psrq.ctx.Fields = append(psrq.ctx.Fields, fields...)
	sbuild := &ProductSpecRelationSelect{ProductSpecRelationQuery: psrq}
	sbuild.label = productspecrelation.Label
	sbuild.flds, sbuild.scan = &psrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductSpecRelationSelect configured with the given aggregations.
func (psrq *ProductSpecRelationQuery) Aggregate(fns ...AggregateFunc) *ProductSpecRelationSelect {
	return psrq.Select().Aggregate(fns...)
}

func (psrq *ProductSpecRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range psrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, psrq); err != nil {
				return err
			}
		}
	}
	for _, f := range psrq.ctx.Fields {
		if !productspecrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if psrq.path != nil {
		prev, err := psrq.path(ctx)
		if err != nil {
			return err
		}
		psrq.sql = prev
	}
	return nil
}

func (psrq *ProductSpecRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductSpecRelation, error) {
	var (
		nodes       = []*ProductSpecRelation{}
		_spec       = psrq.querySpec()
		loadedTypes = [3]bool{
			psrq.withProduct != nil,
			psrq.withSpec != nil,
			psrq.withPackingFee != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductSpecRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductSpecRelation{config: psrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(psrq.modifiers) > 0 {
		_spec.Modifiers = psrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, psrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := psrq.withProduct; query != nil {
		if err := psrq.loadProduct(ctx, query, nodes, nil,
			func(n *ProductSpecRelation, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	if query := psrq.withSpec; query != nil {
		if err := psrq.loadSpec(ctx, query, nodes, nil,
			func(n *ProductSpecRelation, e *ProductSpec) { n.Edges.Spec = e }); err != nil {
			return nil, err
		}
	}
	if query := psrq.withPackingFee; query != nil {
		if err := psrq.loadPackingFee(ctx, query, nodes, nil,
			func(n *ProductSpecRelation, e *AdditionalFee) { n.Edges.PackingFee = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (psrq *ProductSpecRelationQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*ProductSpecRelation, init func(*ProductSpecRelation), assign func(*ProductSpecRelation, *Product)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductSpecRelation)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (psrq *ProductSpecRelationQuery) loadSpec(ctx context.Context, query *ProductSpecQuery, nodes []*ProductSpecRelation, init func(*ProductSpecRelation), assign func(*ProductSpecRelation, *ProductSpec)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductSpecRelation)
	for i := range nodes {
		fk := nodes[i].SpecID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(productspec.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "spec_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (psrq *ProductSpecRelationQuery) loadPackingFee(ctx context.Context, query *AdditionalFeeQuery, nodes []*ProductSpecRelation, init func(*ProductSpecRelation), assign func(*ProductSpecRelation, *AdditionalFee)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductSpecRelation)
	for i := range nodes {
		if nodes[i].PackingFeeID == nil {
			continue
		}
		fk := *nodes[i].PackingFeeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(additionalfee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "packing_fee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (psrq *ProductSpecRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := psrq.querySpec()
	if len(psrq.modifiers) > 0 {
		_spec.Modifiers = psrq.modifiers
	}
	_spec.Node.Columns = psrq.ctx.Fields
	if len(psrq.ctx.Fields) > 0 {
		_spec.Unique = psrq.ctx.Unique != nil && *psrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, psrq.driver, _spec)
}

func (psrq *ProductSpecRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productspecrelation.Table, productspecrelation.Columns, sqlgraph.NewFieldSpec(productspecrelation.FieldID, field.TypeUUID))
	_spec.From = psrq.sql
	if unique := psrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if psrq.path != nil {
		_spec.Unique = true
	}
	if fields := psrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productspecrelation.FieldID)
		for i := range fields {
			if fields[i] != productspecrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if psrq.withProduct != nil {
			_spec.Node.AddColumnOnce(productspecrelation.FieldProductID)
		}
		if psrq.withSpec != nil {
			_spec.Node.AddColumnOnce(productspecrelation.FieldSpecID)
		}
		if psrq.withPackingFee != nil {
			_spec.Node.AddColumnOnce(productspecrelation.FieldPackingFeeID)
		}
	}
	if ps := psrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := psrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := psrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := psrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (psrq *ProductSpecRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(psrq.driver.Dialect())
	t1 := builder.Table(productspecrelation.Table)
	columns := psrq.ctx.Fields
	if len(columns) == 0 {
		columns = productspecrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if psrq.sql != nil {
		selector = psrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if psrq.ctx.Unique != nil && *psrq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range psrq.modifiers {
		m(selector)
	}
	for _, p := range psrq.predicates {
		p(selector)
	}
	for _, p := range psrq.order {
		p(selector)
	}
	if offset := psrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := psrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (psrq *ProductSpecRelationQuery) ForUpdate(opts ...sql.LockOption) *ProductSpecRelationQuery {
	if psrq.driver.Dialect() == dialect.Postgres {
		psrq.Unique(false)
	}
	psrq.modifiers = append(psrq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return psrq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (psrq *ProductSpecRelationQuery) ForShare(opts ...sql.LockOption) *ProductSpecRelationQuery {
	if psrq.driver.Dialect() == dialect.Postgres {
		psrq.Unique(false)
	}
	psrq.modifiers = append(psrq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return psrq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (psrq *ProductSpecRelationQuery) Modify(modifiers ...func(s *sql.Selector)) *ProductSpecRelationSelect {
	psrq.modifiers = append(psrq.modifiers, modifiers...)
	return psrq.Select()
}

// ProductSpecRelationGroupBy is the group-by builder for ProductSpecRelation entities.
type ProductSpecRelationGroupBy struct {
	selector
	build *ProductSpecRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (psrgb *ProductSpecRelationGroupBy) Aggregate(fns ...AggregateFunc) *ProductSpecRelationGroupBy {
	psrgb.fns = append(psrgb.fns, fns...)
	return psrgb
}

// Scan applies the selector query and scans the result into the given value.
func (psrgb *ProductSpecRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psrgb.build.ctx, ent.OpQueryGroupBy)
	if err := psrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductSpecRelationQuery, *ProductSpecRelationGroupBy](ctx, psrgb.build, psrgb, psrgb.build.inters, v)
}

func (psrgb *ProductSpecRelationGroupBy) sqlScan(ctx context.Context, root *ProductSpecRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(psrgb.fns))
	for _, fn := range psrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*psrgb.flds)+len(psrgb.fns))
		for _, f := range *psrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*psrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductSpecRelationSelect is the builder for selecting fields of ProductSpecRelation entities.
type ProductSpecRelationSelect struct {
	*ProductSpecRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (psrs *ProductSpecRelationSelect) Aggregate(fns ...AggregateFunc) *ProductSpecRelationSelect {
	psrs.fns = append(psrs.fns, fns...)
	return psrs
}

// Scan applies the selector query and scans the result into the given value.
func (psrs *ProductSpecRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psrs.ctx, ent.OpQuerySelect)
	if err := psrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductSpecRelationQuery, *ProductSpecRelationSelect](ctx, psrs.ProductSpecRelationQuery, psrs, psrs.inters, v)
}

func (psrs *ProductSpecRelationSelect) sqlScan(ctx context.Context, root *ProductSpecRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(psrs.fns))
	for _, fn := range psrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*psrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (psrs *ProductSpecRelationSelect) Modify(modifiers ...func(s *sql.Selector)) *ProductSpecRelationSelect {
	psrs.modifiers = append(psrs.modifiers, modifiers...)
	return psrs
}
