// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
	"gitlab.jiguang.dev/pos-dine/dine/ent/setmealdetail"
)

// SetMealDetailDelete is the builder for deleting a SetMealDetail entity.
type SetMealDetailDelete struct {
	config
	hooks    []Hook
	mutation *SetMealDetailMutation
}

// Where appends a list predicates to the SetMealDetailDelete builder.
func (smdd *SetMealDetailDelete) Where(ps ...predicate.SetMealDetail) *SetMealDetailDelete {
	smdd.mutation.Where(ps...)
	return smdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smdd *SetMealDetailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, smdd.sqlExec, smdd.mutation, smdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smdd *SetMealDetailDelete) ExecX(ctx context.Context) int {
	n, err := smdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smdd *SetMealDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(setmealdetail.Table, sqlgraph.NewFieldSpec(setmealdetail.FieldID, field.TypeInt))
	if ps := smdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smdd.mutation.done = true
	return affected, err
}

// SetMealDetailDeleteOne is the builder for deleting a single SetMealDetail entity.
type SetMealDetailDeleteOne struct {
	smdd *SetMealDetailDelete
}

// Where appends a list predicates to the SetMealDetailDelete builder.
func (smddo *SetMealDetailDeleteOne) Where(ps ...predicate.SetMealDetail) *SetMealDetailDeleteOne {
	smddo.smdd.mutation.Where(ps...)
	return smddo
}

// Exec executes the deletion query.
func (smddo *SetMealDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := smddo.smdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{setmealdetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smddo *SetMealDetailDeleteOne) ExecX(ctx context.Context) {
	if err := smddo.Exec(ctx); err != nil {
		panic(err)
	}
}
