// Code generated by ent, DO NOT EDIT.

package merchantbusinesstype

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"gitlab.jiguang.dev/pos-dine/dine/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldDeletedAt, v))
}

// MerchantID applies equality check predicate on the "merchant_id" field. It's identical to MerchantIDEQ.
func MerchantID(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldMerchantID, v))
}

// TypeCode applies equality check predicate on the "type_code" field. It's identical to TypeCodeEQ.
func TypeCode(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldTypeCode, v))
}

// TypeName applies equality check predicate on the "type_name" field. It's identical to TypeNameEQ.
func TypeName(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldTypeName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldDeletedAt, v))
}

// MerchantIDEQ applies the EQ predicate on the "merchant_id" field.
func MerchantIDEQ(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldMerchantID, v))
}

// MerchantIDNEQ applies the NEQ predicate on the "merchant_id" field.
func MerchantIDNEQ(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldMerchantID, v))
}

// MerchantIDIn applies the In predicate on the "merchant_id" field.
func MerchantIDIn(vs ...uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldMerchantID, vs...))
}

// MerchantIDNotIn applies the NotIn predicate on the "merchant_id" field.
func MerchantIDNotIn(vs ...uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldMerchantID, vs...))
}

// MerchantIDGT applies the GT predicate on the "merchant_id" field.
func MerchantIDGT(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldMerchantID, v))
}

// MerchantIDGTE applies the GTE predicate on the "merchant_id" field.
func MerchantIDGTE(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldMerchantID, v))
}

// MerchantIDLT applies the LT predicate on the "merchant_id" field.
func MerchantIDLT(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldMerchantID, v))
}

// MerchantIDLTE applies the LTE predicate on the "merchant_id" field.
func MerchantIDLTE(v uuid.UUID) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldMerchantID, v))
}

// MerchantIDIsNil applies the IsNil predicate on the "merchant_id" field.
func MerchantIDIsNil() predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIsNull(FieldMerchantID))
}

// MerchantIDNotNil applies the NotNil predicate on the "merchant_id" field.
func MerchantIDNotNil() predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotNull(FieldMerchantID))
}

// TypeCodeEQ applies the EQ predicate on the "type_code" field.
func TypeCodeEQ(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldTypeCode, v))
}

// TypeCodeNEQ applies the NEQ predicate on the "type_code" field.
func TypeCodeNEQ(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldTypeCode, v))
}

// TypeCodeIn applies the In predicate on the "type_code" field.
func TypeCodeIn(vs ...string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldTypeCode, vs...))
}

// TypeCodeNotIn applies the NotIn predicate on the "type_code" field.
func TypeCodeNotIn(vs ...string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldTypeCode, vs...))
}

// TypeCodeGT applies the GT predicate on the "type_code" field.
func TypeCodeGT(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldTypeCode, v))
}

// TypeCodeGTE applies the GTE predicate on the "type_code" field.
func TypeCodeGTE(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldTypeCode, v))
}

// TypeCodeLT applies the LT predicate on the "type_code" field.
func TypeCodeLT(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldTypeCode, v))
}

// TypeCodeLTE applies the LTE predicate on the "type_code" field.
func TypeCodeLTE(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldTypeCode, v))
}

// TypeCodeContains applies the Contains predicate on the "type_code" field.
func TypeCodeContains(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldContains(FieldTypeCode, v))
}

// TypeCodeHasPrefix applies the HasPrefix predicate on the "type_code" field.
func TypeCodeHasPrefix(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldHasPrefix(FieldTypeCode, v))
}

// TypeCodeHasSuffix applies the HasSuffix predicate on the "type_code" field.
func TypeCodeHasSuffix(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldHasSuffix(FieldTypeCode, v))
}

// TypeCodeEqualFold applies the EqualFold predicate on the "type_code" field.
func TypeCodeEqualFold(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEqualFold(FieldTypeCode, v))
}

// TypeCodeContainsFold applies the ContainsFold predicate on the "type_code" field.
func TypeCodeContainsFold(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldContainsFold(FieldTypeCode, v))
}

// TypeNameEQ applies the EQ predicate on the "type_name" field.
func TypeNameEQ(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEQ(FieldTypeName, v))
}

// TypeNameNEQ applies the NEQ predicate on the "type_name" field.
func TypeNameNEQ(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNEQ(FieldTypeName, v))
}

// TypeNameIn applies the In predicate on the "type_name" field.
func TypeNameIn(vs ...string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldIn(FieldTypeName, vs...))
}

// TypeNameNotIn applies the NotIn predicate on the "type_name" field.
func TypeNameNotIn(vs ...string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldNotIn(FieldTypeName, vs...))
}

// TypeNameGT applies the GT predicate on the "type_name" field.
func TypeNameGT(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGT(FieldTypeName, v))
}

// TypeNameGTE applies the GTE predicate on the "type_name" field.
func TypeNameGTE(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldGTE(FieldTypeName, v))
}

// TypeNameLT applies the LT predicate on the "type_name" field.
func TypeNameLT(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLT(FieldTypeName, v))
}

// TypeNameLTE applies the LTE predicate on the "type_name" field.
func TypeNameLTE(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldLTE(FieldTypeName, v))
}

// TypeNameContains applies the Contains predicate on the "type_name" field.
func TypeNameContains(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldContains(FieldTypeName, v))
}

// TypeNameHasPrefix applies the HasPrefix predicate on the "type_name" field.
func TypeNameHasPrefix(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldHasPrefix(FieldTypeName, v))
}

// TypeNameHasSuffix applies the HasSuffix predicate on the "type_name" field.
func TypeNameHasSuffix(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldHasSuffix(FieldTypeName, v))
}

// TypeNameEqualFold applies the EqualFold predicate on the "type_name" field.
func TypeNameEqualFold(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldEqualFold(FieldTypeName, v))
}

// TypeNameContainsFold applies the ContainsFold predicate on the "type_name" field.
func TypeNameContainsFold(v string) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.FieldContainsFold(FieldTypeName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MerchantBusinessType) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MerchantBusinessType) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MerchantBusinessType) predicate.MerchantBusinessType {
	return predicate.MerchantBusinessType(sql.NotPredicates(p))
}
