-- Modify "categories" table
ALTER TABLE `categories` ADD CONSTRAINT `categories_categories_children` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "orders" table
CREATE TABLE `orders` (
  `id` char(36) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  `merchant_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `business_date` varchar(255) NOT NULL,
  `shift_no` varchar(255) NULL,
  `order_no` varchar(255) NOT NULL,
  `order_type` enum('SALE','REFUND','PARTIAL_REFUND') NOT NULL DEFAULT "SALE",
  `origin_order_id` varchar(255) NULL,
  `refund` json NULL,
  `opened_at` timestamp NULL,
  `placed_at` timestamp NULL,
  `paid_at` timestamp NULL,
  `completed_at` timestamp NULL,
  `opened_by` varchar(255) NULL,
  `placed_by` varchar(255) NULL,
  `paid_by` varchar(255) NULL,
  `dining_mode` enum('DINE_IN','TAKEAWAY') NOT NULL,
  `order_status` enum('DRAFT','PLACED','IN_PROGRESS','READY','COMPLETED','CANCELLED','VOIDED','MERGED') NOT NULL DEFAULT "DRAFT",
  `payment_status` enum('UNPAID','PAYING','PARTIALLY_PAID','PAID','PARTIALLY_REFUNDED','REFUNDED') NOT NULL DEFAULT "UNPAID",
  `fulfillment_status` enum('NONE','IN_RESTAURANT','SERVED','PICKUP_PENDING','PICKED_UP','DELIVERING','DELIVERED') NULL,
  `table_status` enum('OPENED','TRANSFERRED','RELEASED') NULL,
  `table_id` varchar(255) NULL,
  `table_name` varchar(255) NULL,
  `table_capacity` bigint NULL,
  `guest_count` bigint NULL,
  `merged_to_order_id` varchar(255) NULL,
  `merged_at` timestamp NULL,
  `store` json NOT NULL,
  `channel` json NOT NULL,
  `pos` json NOT NULL,
  `cashier` json NOT NULL,
  `member` json NULL,
  `takeaway` json NULL,
  `cart` json NOT NULL,
  `products` json NOT NULL,
  `promotions` json NULL,
  `coupons` json NULL,
  `tax_rates` json NULL,
  `fees` json NULL,
  `payments` json NULL,
  `refunds_products` json NULL,
  `amount` json NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_deleted_at` (`deleted_at`),
  INDEX `order_merchant_id` (`merchant_id`),
  INDEX `order_merged_to_order_id` (`merged_to_order_id`),
  INDEX `order_origin_order_id` (`origin_order_id`),
  INDEX `order_store_id` (`store_id`),
  INDEX `order_store_id_business_date` (`store_id`, `business_date`),
  UNIQUE INDEX `order_store_id_order_no_deleted_at` (`store_id`, `order_no`, `deleted_at`),
  INDEX `order_store_id_order_status` (`store_id`, `order_status`),
  INDEX `order_store_id_payment_status` (`store_id`, `payment_status`),
  INDEX `order_table_id` (`table_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;
