-- Create "admin_users" table
CREATE TABLE `admin_users` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `username` varchar(100) NOT NULL, `hashed_password` varchar(255) NOT NULL, `nickname` varchar(255) NOT NULL, PRIMARY KEY (`id`), INDEX `adminuser_deleted_at` (`deleted_at`), UNIQUE INDEX `adminuser_username_deleted_at` (`username`, `deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "stores" table
CREATE TABLE `stores` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), INDEX `store_deleted_at` (`deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "backend_users" table
CREATE TABLE `backend_users` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `username` varchar(100) NOT NULL, `hashed_password` varchar(255) NOT NULL, `nickname` varchar(255) NOT NULL, `store_backend_user` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `backenduser_deleted_at` (`deleted_at`), UNIQUE INDEX `backenduser_username_deleted_at` (`username`, `deleted_at`), UNIQUE INDEX `store_backend_user` (`store_backend_user`), CONSTRAINT `backend_users_stores_backend_user` FOREIGN KEY (`store_backend_user`) REFERENCES `stores` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "table_areas" table
CREATE TABLE `table_areas` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, `table_count` bigint NULL, PRIMARY KEY (`id`), INDEX `tablearea_deleted_at` (`deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "dine_tables" table
CREATE TABLE `dine_tables` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, `seat_count` bigint NOT NULL, `status` bigint NOT NULL DEFAULT 1, `area_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `dine_tables_table_areas_dinetables` (`area_id`), INDEX `dinetable_deleted_at` (`deleted_at`), CONSTRAINT `dine_tables_table_areas_dinetables` FOREIGN KEY (`area_id`) REFERENCES `table_areas` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "frontend_users" table
CREATE TABLE `frontend_users` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `username` varchar(100) NOT NULL, `hashed_password` varchar(255) NOT NULL, `nickname` varchar(255) NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `frontend_users_stores_frontend_users` (`store_id`), INDEX `frontenduser_deleted_at` (`deleted_at`), UNIQUE INDEX `frontenduser_username_deleted_at` (`username`, `deleted_at`), CONSTRAINT `frontend_users_stores_frontend_users` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "orders" table
CREATE TABLE `orders` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `no` varchar(255) NOT NULL, `type` enum('dine_in') NOT NULL, `source` enum('offline') NOT NULL, `status` enum('unpaid','part_paid','paid','canceled') NOT NULL, `total` decimal(10,2) NOT NULL, `discount` decimal(10,2) NOT NULL, `last_paid_at` timestamp NULL, `member_id` bigint NOT NULL, `member_name` varchar(255) NOT NULL, `member_phone` varchar(255) NOT NULL, `table_id` bigint NOT NULL, `creator_id` bigint NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `no` (`no`), INDEX `order_deleted_at` (`deleted_at`), INDEX `orders_frontend_users_orders` (`creator_id`), INDEX `orders_stores_orders` (`store_id`), CONSTRAINT `orders_frontend_users_orders` FOREIGN KEY (`creator_id`) REFERENCES `frontend_users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `orders_stores_orders` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_items" table
CREATE TABLE `order_items` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `product_id` bigint NOT NULL, `name` varchar(255) NOT NULL, `type` bigint NOT NULL DEFAULT 1, `allow_point_pay` bool NOT NULL DEFAULT 1, `quantity` decimal(10,2) NOT NULL, `price` decimal(10,2) NOT NULL, `amount` decimal(10,2) NOT NULL, `product_snapshot` json NOT NULL, `order_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `order_items_orders_items` (`order_id`), INDEX `orderitem_deleted_at` (`deleted_at`), CONSTRAINT `order_items_orders_items` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "order_item_set_meal_details" table
CREATE TABLE `order_item_set_meal_details` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `type` bigint NOT NULL DEFAULT 1, `set_meal_price` decimal(10,2) NOT NULL, `set_meal_id` bigint NOT NULL, `product_id` bigint NOT NULL, `quantity` decimal(10,2) NOT NULL, `product_snapshot` json NOT NULL, `order_item_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `order_item_set_meal_details_order_items_set_meal_details` (`order_item_id`), INDEX `orderitemsetmealdetail_deleted_at` (`deleted_at`), CONSTRAINT `order_item_set_meal_details_order_items_set_meal_details` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "attrs" table
CREATE TABLE `attrs` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `attr_deleted_at` (`deleted_at`), INDEX `attr_store_id_name` (`store_id`, `name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "categories" table
CREATE TABLE `categories` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, `parent_id` bigint NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `category_deleted_at` (`deleted_at`), INDEX `category_store_id_name` (`store_id`, `name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "units" table
CREATE TABLE `units` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `unit_deleted_at` (`deleted_at`), INDEX `unit_store_id_name` (`store_id`, `name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "products" table
CREATE TABLE `products` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, `type` bigint NOT NULL DEFAULT 1, `images` json NULL, `price` decimal(10,2) NULL, `status` bigint NOT NULL DEFAULT 1, `sale_status` bigint NOT NULL DEFAULT 1, `allow_point_pay` bool NOT NULL DEFAULT 1, `category_id` bigint NOT NULL, `unit_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `product_deleted_at` (`deleted_at`), INDEX `product_sale_status` (`sale_status`), INDEX `product_status` (`status`), INDEX `product_store_id_name` (`store_id`, `name`), INDEX `product_type` (`type`), INDEX `products_categories_products` (`category_id`), INDEX `products_units_products` (`unit_id`), CONSTRAINT `products_categories_products` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `products_units_products` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "product_attrs" table
CREATE TABLE `product_attrs` (`product_id` bigint NOT NULL, `attr_id` bigint NOT NULL, PRIMARY KEY (`product_id`, `attr_id`), INDEX `product_attrs_attr_id` (`attr_id`), CONSTRAINT `product_attrs_attr_id` FOREIGN KEY (`attr_id`) REFERENCES `attrs` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `product_attrs_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "recipes" table
CREATE TABLE `recipes` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `recipe_deleted_at` (`deleted_at`), INDEX `recipe_store_id_name` (`store_id`, `name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "product_recipes" table
CREATE TABLE `product_recipes` (`product_id` bigint NOT NULL, `recipe_id` bigint NOT NULL, PRIMARY KEY (`product_id`, `recipe_id`), INDEX `product_recipes_recipe_id` (`recipe_id`), CONSTRAINT `product_recipes_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `product_recipes_recipe_id` FOREIGN KEY (`recipe_id`) REFERENCES `recipes` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "specs" table
CREATE TABLE `specs` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `store_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `spec_deleted_at` (`deleted_at`), INDEX `spec_store_id_name` (`store_id`, `name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "product_specs" table
CREATE TABLE `product_specs` (`id` bigint NOT NULL AUTO_INCREMENT, `price` decimal(10,2) NOT NULL, `sale_status` bigint NOT NULL DEFAULT 1, `product_id` bigint NOT NULL, `spec_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `product_specs_specs_product_specs` (`spec_id`), UNIQUE INDEX `productspec_product_id_spec_id` (`product_id`, `spec_id`), CONSTRAINT `product_specs_products_product_specs` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `product_specs_specs_product_specs` FOREIGN KEY (`spec_id`) REFERENCES `specs` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "set_meal_details" table
CREATE TABLE `set_meal_details` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `price` decimal(10,2) NOT NULL, `quantity` decimal(8,3) NOT NULL, `set_meal_id` bigint NOT NULL, `product_id` bigint NOT NULL, `product_spec_id` bigint NULL, PRIMARY KEY (`id`), INDEX `set_meal_details_product_specs_set_meal_details` (`product_spec_id`), INDEX `set_meal_details_products_included_in_set_meals` (`product_id`), INDEX `set_meal_details_products_set_meal_details` (`set_meal_id`), INDEX `setmealdetail_deleted_at` (`deleted_at`), CONSTRAINT `set_meal_details_product_specs_set_meal_details` FOREIGN KEY (`product_spec_id`) REFERENCES `product_specs` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `set_meal_details_products_included_in_set_meals` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `set_meal_details_products_set_meal_details` FOREIGN KEY (`set_meal_id`) REFERENCES `products` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
