-- Create "refund_orders" table
CREATE TABLE `refund_orders` (
  `id` char(36) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  `merchant_id` char(36) NOT NULL,
  `store_id` char(36) NOT NULL,
  `business_date` varchar(255) NOT NULL,
  `shift_no` varchar(255) NULL,
  `refund_no` varchar(255) NOT NULL,
  `origin_order_id` char(36) NOT NULL,
  `origin_order_no` varchar(255) NOT NULL,
  `origin_paid_at` timestamp NULL,
  `origin_amount_paid` decimal(10, 4) NULL,
  `refund_type` enum ('FULL', 'PARTIAL') NOT NULL,
  `refund_status` enum (
    'PENDING',
    'PROCESSING',
    'COMPLETED',
    'FAILED',
    'CANCELLED'
  ) NOT NULL DEFAULT "PENDING",
  `refund_reason_code` varchar(255) NULL,
  `refund_reason` longtext NULL,
  `refunded_by` char(36) NULL,
  `refunded_by_name` varchar(255) NULL,
  `approved_by` char(36) NULL,
  `approved_by_name` varchar(255) NULL,
  `approved_at` timestamp NULL,
  `refunded_at` timestamp NULL,
  `store` json NOT NULL,
  `channel` enum ('POS') NOT NULL DEFAULT "POS",
  `pos` json NOT NULL,
  `cashier` json NOT NULL,
  `refund_amount` json NOT NULL,
  `refund_payments` json NULL,
  `remark` varchar(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `refundorder_business_date` (`business_date`),
  INDEX `refundorder_deleted_at` (`deleted_at`),
  INDEX `refundorder_merchant_id` (`merchant_id`),
  INDEX `refundorder_origin_order_id` (`origin_order_id`),
  INDEX `refundorder_refund_status` (`refund_status`),
  INDEX `refundorder_store_id` (`store_id`),
  UNIQUE INDEX `refundorder_store_id_refund_no_deleted_at` (`store_id`, `refund_no`, `deleted_at`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

-- Create "refund_order_products" table
CREATE TABLE `refund_order_products` (
  `id` char(36) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  `origin_order_product_id` char(36) NOT NULL,
  `origin_order_item_id` varchar(255) NULL,
  `product_id` char(36) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_type` enum ('normal', 'set_meal') NOT NULL DEFAULT "normal",
  `category` json NULL,
  `unit_id` char(36) NULL,
  `main_image` varchar(512) NOT NULL DEFAULT "",
  `description` varchar(2000) NOT NULL DEFAULT "",
  `origin_qty` bigint NOT NULL,
  `origin_price` decimal(10, 4) NULL,
  `origin_subtotal` decimal(10, 4) NULL,
  `origin_discount` decimal(10, 4) NULL,
  `origin_tax` decimal(10, 4) NULL,
  `origin_total` decimal(10, 4) NULL,
  `refund_qty` bigint NOT NULL,
  `refund_subtotal` decimal(10, 4) NULL,
  `refund_discount` decimal(10, 4) NULL,
  `refund_tax` decimal(10, 4) NULL,
  `refund_total` decimal(10, 4) NULL,
  `groups` json NULL,
  `spec_relations` json NULL,
  `attr_relations` json NULL,
  `refund_reason` longtext NULL,
  `refund_order_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `refundorderproduct_deleted_at` (`deleted_at`),
  INDEX `refundorderproduct_origin_order_product_id` (`origin_order_product_id`),
  INDEX `refundorderproduct_product_id` (`product_id`),
  UNIQUE INDEX `refundorderproduct_refund_order_68af4e7ee9df0824fcbfba202d43d240` (
    `refund_order_id`,
    `origin_order_product_id`,
    `deleted_at`
  ),
  INDEX `refundorderproduct_refund_order_id` (`refund_order_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;
