-- Create "orders" table
CREATE TABLE `orders` (
  `id` char(36) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  `merchant_id` char(36) NOT NULL,
  `store_id` char(36) NOT NULL,
  `business_date` varchar(255) NOT NULL,
  `shift_no` varchar(255) NULL,
  `order_no` varchar(255) NOT NULL,
  `order_type` enum ('SALE', 'REFUND', 'PARTIAL_REFUND') NOT NULL DEFAULT "SALE",
  `refund` json NULL,
  `placed_at` timestamp NULL,
  `paid_at` timestamp NULL,
  `completed_at` timestamp NULL,
  `placed_by` varchar(255) NULL,
  `dining_mode` enum ('DINE_IN') NOT NULL DEFAULT "DINE_IN",
  `order_status` enum ('PLACED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT "PLACED",
  `payment_status` enum ('UNPAID', 'PAYING', 'PAID', 'REFUNDED') NOT NULL DEFAULT "UNPAID",
  `table_id` varchar(255) NULL,
  `table_name` varchar(255) NULL,
  `guest_count` bigint NULL,
  `store` json NOT NULL,
  `channel` enum ('POS') NOT NULL DEFAULT "POS",
  `pos` json NOT NULL,
  `cashier` json NOT NULL,
  `tax_rates` json NULL,
  `fees` json NULL,
  `payments` json NULL,
  `amount` json NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_deleted_at` (`deleted_at`),
  INDEX `order_merchant_id` (`merchant_id`),
  INDEX `order_order_status` (`order_status`),
  INDEX `order_payment_status` (`payment_status`),
  INDEX `order_store_id` (`store_id`),
  UNIQUE INDEX `order_store_id_order_no_deleted_at` (`store_id`, `order_no`, `deleted_at`),
  INDEX `order_table_id` (`table_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;

-- Create "order_products" table
CREATE TABLE `order_products` (
  `id` char(36) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` bigint NOT NULL DEFAULT 0,
  `order_item_id` varchar(255) NOT NULL,
  `index` bigint NOT NULL DEFAULT 0,
  `product_id` char(36) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_type` enum ('normal', 'set_meal') NOT NULL DEFAULT "normal",
  `category_id` char(36) NULL,
  `menu_id` char(36) NULL,
  `unit_id` char(36) NULL,
  `support_types` json NULL,
  `sale_status` enum ('on_sale', 'off_sale') NULL,
  `sale_channels` json NULL,
  `main_image` varchar(512) NOT NULL DEFAULT "",
  `description` varchar(2000) NOT NULL DEFAULT "",
  `qty` bigint NOT NULL DEFAULT 1,
  `subtotal` decimal(10, 4) NULL,
  `discount_amount` decimal(10, 4) NULL,
  `amount_before_tax` decimal(10, 4) NULL,
  `tax_rate` decimal(10, 4) NULL,
  `tax` decimal(10, 4) NULL,
  `amount_after_tax` decimal(10, 4) NULL,
  `total` decimal(10, 4) NULL,
  `promotion_discount` decimal(10, 4) NULL,
  `void_qty` bigint NOT NULL DEFAULT 0,
  `void_amount` decimal(10, 4) NULL,
  `refund_reason` varchar(255) NULL,
  `refunded_by` varchar(255) NULL,
  `refunded_at` timestamp NULL,
  `note` varchar(255) NULL,
  `estimated_cost_price` decimal(10, 4) NULL,
  `delivery_cost_price` decimal(10, 4) NULL,
  `set_meal_groups` json NULL,
  `spec_relations` json NULL,
  `attr_relations` json NULL,
  `order_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `orderproduct_deleted_at` (`deleted_at`),
  INDEX `orderproduct_order_id` (`order_id`),
  UNIQUE INDEX `orderproduct_order_id_order_item_id` (`order_id`, `order_item_id`),
  INDEX `orderproduct_product_id` (`product_id`)
) CHARSET utf8mb4 COLLATE utf8mb4_bin;
